### ISSUE TITLE
删除选中列、行操作没有暴露操作方法吗

### ISSUE THREAD

**Issue by Alisa0026** [mengshukeji/Luckysheet#10]
看demo删除选中列行不生效，似乎文档也没提供对应的触发方法

**Comment by liuyang3688** [comment]
不是不生效 是有bug 需要自己修改

**Comment by mengshukeji** [comment]
> 看demo删除选中列行不生效，似乎文档也没提供对应的触发方法

可以删除选中列和行，只是字母顺序和数字顺序不变，参考excel。
具体的api后续会整理
