### ISSUE TITLE
汇总数据后再添加行汇总的数据不正确[BUG]Find a bug

### ISSUE THREAD

**Issue by qd98zhq** [mengshukeji/Luckysheet#100]
汇总数据后再添加行汇总的数据不正确，好像是翻倍了，我录制了一个视频，看了就知道了。可惜我不知如何上传操作过程的视频给你。

**Comment by mengshukeji** [comment]
汇总数据是怎么操作的？视频可以传输到腾讯视频或者优酷视频再发出链接。

**Comment by qd98zhq** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mengshukeji/Luckysheet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月27日(星期二) 下午2:59
收件人:&nbsp;"mengshukeji/Luckysheet"<Luckysheet@noreply.github.com&gt;;
抄送:&nbsp;"钟海全"<249321675@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mengshukeji/Luckysheet] 汇总数据后再添加行汇总的数据不正确[BUG]Find a bug (#100)





 
汇总数据是怎么操作的？视频可以传输到腾讯视频或者优酷视频再发出链接。

**Comment by mengshukeji** [comment]
感谢反馈，没有具体复现步骤，我们将会关闭此issue,很抱歉。如果还有疑问，再新开一个issue.
