### ISSUE TITLE
I don't konw how to contact with server with Lucksheet

### ISSUE THREAD

**Issue by flyhawkxjtu** [mengshukeji/Luckysheet#103]
for example:
1. server-side has one excel docment, how to shw this one on web explore?
2. I use Luckysheet to create a new excel online , how to save this document to server?

thanks.

**Comment by huiali** [comment]
+1

**Comment by huiali** [comment]
+1

**Comment by wbfsa** [comment]
Yes, you can save json to server with method: luckysheet.getLuckysheetfile(). Later we will open source back-end collaboration source code.
