### ISSUE TITLE
背景颜色为灰色，可以使表格平铺，没有灰色背景吗？

### ISSUE THREAD

**Issue by Dirty-nunu** [mengshukeji/Luckysheet#1041]
在使用luckysheet时会出现背景颜色为灰色，可以自定义背景颜色吗？或者可以使单元格铺满，不显示灰色背
![luckysheet](https://user-images.githubusercontent.com/99306315/171119036-d4ce702f-0247-41c7-8f7c-6238e02e4289.png)
景

**Comment by Dirty-nunu** [comment]
已解决

**Comment by qdm-web** [comment]
> 已解决

请问怎么解决的

**Comment by shenjipo** [comment]
> 已解决

请问咋解决的
