### ISSUE TITLE
【禁止拖拽功能】鼠标操作表格时候拖拽太容易被触发了 而且对这个功能不是特别需要，建议增加原生的禁止拖拽

### ISSUE THREAD

**Issue by lhtuling** [mengshukeji/Luckysheet#1078]
如题
鼠标操作时候特别容易误拖动

**Comment by luncheon** [comment]
This is not an official answer, but I think that if you do this after initialization is complete, you can stop moving cells by dragging.

```js
$("#luckysheet-cell-main div.luckysheet-cs-draghandle").off('mousedown')
```

Relevant source:
https://github.com/mengshukeji/Luckysheet/blob/v2.1.13/src/controllers/handler.js#L4291

**Comment by lhtuling** [comment]
> 

感谢你的回答!帮大忙了  能实现功能即可  官方能直接搞个配置更好!

**Comment by luncheon** [comment]
This CSS solution might be better.

```css
.luckysheet-cs-draghandle {
  display: none !important;
}
```
