### ISSUE TITLE
边框线第一列左边框与第一行上边框缺失

### ISSUE THREAD

**Issue by SuyongSun** [mengshukeji/Luckysheet#11]
几个问题反馈：
1、设置边框线的时候第一列左边框与第一行上边框设置无效，猜测因为与行、列标题相接部分处理的问题。
2、如果只设置左或右边框，中间会有一个像素的空白，连续单元格之间的仅设置左右边框时看起来就是不连续的，这部分在打印效果上会有些问题。
3、在设置列宽时，如果单元格为“折行显示”，当设置的列宽不足以显示一个字符宽时整个表格会崩溃。在列宽设置或做导入时，可能需要增加对列宽设置时的判断，无法使用折行模式时需要改为其他模式。另外：目前溢出模式与截断模式相同，溢出模式时未显示多出的字符到后续单元格浮层上。

**Comment by SuyongSun** [comment]
另外如果只设置左或右边框，中间会有一个像素的空白，连续单元格之间的仅设置左右边框时看起来就是不连续的，这部分在打印效果上会有些问题。

**Comment by mengshukeji** [comment]
> 几个问题反馈：
> 1、设置边框线的时候第一列左边框与第一行上边框设置无效，猜测因为与行、列标题相接部分处理的问题。
> 2、如果只设置左或右边框，中间会有一个像素的空白，连续单元格之间的仅设置左右边框时看起来就是不连续的，这部分在打印效果上会有些问题。
> 3、在设置列宽时，如果单元格为“折行显示”，当设置的列宽不足以显示一个字符宽时整个表格会崩溃。在列宽设置或做导入时，可能需要增加对列宽设置时的判断，无法使用折行模式时需要改为其他模式。另外：目前溢出模式与截断模式相同，溢出模式时未显示多出的字符到后续单元格浮层上。

1. 与excel保持一致的，可参考excel
2. 空白问题后续版本会修复
3. 折行显示bug正在修复。溢出暂时不支持，后续版本会加上

**Comment by SuyongSun** [comment]
对于第一点明白处理上同excel，只是在网页端使用中会有几个问题，比如：
luckysheet的截图功能应该是用html2canvas做的，那么截图中第一行的上边线与第一列的左边线就会截取不到。
同理如果打印也是用这个方式来获取打印区域进行打印，同样会丢失上边线和左边线。

以上供参考。
