### ISSUE TITLE
[BUG]协同编辑时，删除一列后，刷新页面后报错。

### ISSUE THREAD

**Issue by jgs555** [mengshukeji/Luckysheet#1155]
[Cannot read properties of undefined (reading '0')](luckysheet.umd.js:9 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0'))

**Comment by jgs555** [comment]
接口返回如下：
[{"color":"","list_id":"1079500#-8803#7c45f52b7d01486d88bc53cb17dcd2c3","jfgird_select_save":[{"column":[0,0],"width_move":73,"top_move":0,"top":0,"left":0,"column_focus":0,"column_select":true,"width":73,"left_move":0,"row":[0,83],"row_focus":0,"height_move":1679,"height":19}],"rh_height":1790,"visibledatarow":[],"calcChain":[],"luckysheet_conditionformat_save":[],"celldata":[{"r":0,"c":0,"v":{"ct":{"t":"n","fa":"General"},"bg":"#ffff00","v":2,"m":"2"}}],"ch_width":4748,"row":84,"scrollLeft":0,"id":357452726063468544,"order":0,"hyperlink":{},"column":60,"index":"1","luckysheet_alternateformat_save":[],"filter_select":"null","visibledatacolumn":[],"scrollTop":0,"block_id":"fblock","filter":"null","rowsplit":[],"jfgrid_selection_range":{},"dataVerification":{},"name":"Sheet1","chart":[],"config":{"colhidden":{},"merge":{},"columnlen":{}},"status":1},{"color":"","list_id":"1079500#-8803#7c45f52b7d01486d88bc53cb17dcd2c3","column":60,"index":"2","jfgird_select_save":[],"rh_height":1790,"visibledatacolumn":[],"scrollTop":0,"block_id":"fblock","rowsplit":[],"visibledatarow":[],"jfgrid_selection_range":{},"name":"Sheet2","ch_width":4748,"row":84,"scrollLeft":0,"id":139400313311449088,"chart":[],"config":{},"order":1,"status":0},{"color":"","list_id":"1079500#-8803#7c45f52b7d01486d88bc53cb17dcd2c3","column":60,"index":"3","jfgird_select_save":[],"rh_height":1790,"visibledatacolumn":[],"scrollTop":0,"block_id":"fblock","rowsplit":[],"visibledatarow":[],"jfgrid_selection_range":{},"name":"Sheet3","ch_width":4748,"row":84,"scrollLeft":0,"id":139400313311449089,"chart":[],"config":{},"order":2,"status":0}]

**Comment by HengCC** [comment]
你这个只能自己debug了. 官方现在估计也没人解决你的问题. 但是你这个问题我觉得我可以帮到你.  之前有人提的PR里面提交了错误的代码.  参考如下修改. 
![image](https://user-images.githubusercontent.com/6167532/189818050-8bfea8a6-2fe2-4a93-b867-40183ef0663c.png)
左边是错误的示例. 右边是修改后. 直接清空type=1的代码就行了. 那个是发给自己的信息. 如果不生效你就自己debug下吧

**Comment by HengCC** [comment]
最初是这个提交合并的 https://github.com/mengshukeji/Luckysheet/commit/0f0d983a35b98e033e024258c98f5078488a123c

**Comment by jgs555** [comment]
> 是的，这个问题解决了，然后在点击任意单元格的时候，控制台又报错，刚刚就定位到这段代码了，感谢帮助。



> 你只能自己调试了。官方现在估计没人解决你的问题。你这个问题我觉得我可以帮到你。在某人提的 PR 里面提交了错误的代码之前。参考如下修改。 向是错误的例子。右是修改后。直接清空type=1的代码就行了。那是发给自己的信息。如果不生效你就自己调试下吧`server.js` ![图片](https://user-images.githubusercontent.com/6167532/189818050-8bfea8a6-2fe2-4a93-b867-40183ef0663c.png)

**Comment by jgs555** [comment]
> 是错误的例子。右是修改后。直接清空type=1的代码就行了。那是发给自己的信息。如果不生效你就自己调试下吧`server.js`

**Comment by HengCC** [comment]
如果你也在搞协同编辑. 建议你看看我之前提交的issue.  有的我给了解决方案. 有的没给.  坑还是比较多.

**Comment by jgs555** [comment]
> 

有你踩过坑后的demo分享吗？我现在遇到的是后台只报错最新的一次数据，比如协同时候，我在1列填了1，2列填了2，刷新一下，只有2列的2了。

**Comment by jgs555** [comment]
@HengCC 有你踩过坑后的demo分享吗？我现在遇到的是后台只报错最新的一次数据，比如协同时候，我在1列填了1，2列填了2，刷新一下，只有2列的2了。

**Comment by HengCC** [comment]
那是因为官方的后台demo部分也有问题.  自己看协议 重写一个基于ws的后端服务吧. 我这边的方案是重写了一个后端服务. 所以现在勉强也能用用. 还在试用阶段. 数据到是没丢了.  之前也和你这个一样

**Comment by jgs555** [comment]
@HengCC我不会后台，能分享一下你现在的后台吗？

**Comment by HengCC** [comment]
...我懒. 和业务代码混一起的.  没时间剥开....
