### ISSUE TITLE
验证问题

### ISSUE THREAD

**Issue by 1012511661** [mengshukeji/Luckysheet#116]
format.js  里面 genarate() 判断格式 第1961行 这个else 也这边感觉有点不对，初始化要是 某种类型  要是输入其他类型 这里会默认给转为  General 类型 ，这样就做不成用户输入和指定类型不对 给友好提醒了

**Comment by 1012511661** [comment]
format.js  里面 genarate() 判断格式 第1961行 这个else 也这边感觉有点不合适，初始化要是 某种类型  要是输入其他类型 这里会默认给转为  General 类型 ，这样就做不成用户输入和指定类型不对 给友好提醒了

**Comment by mengshukeji** [comment]
很好的想法。

如果您这边是二次开发的需求，可以先自行定制这类限制。
Luckysheet设计是用户输入的类型优先，没有提供指定类型限制，后续我们会考虑优化。
