### ISSUE TITLE
[Feature request] Demo/docs for rtc collaboration

### ISSUE THREAD

**Issue by lofcz** [mengshukeji/Luckysheet#118]
**Is your feature request related to a problem? Please describe.**
In docs at point "share" it is mentioned that Luckysheet is able of simultaneous editing of a sheet by multiple users. https://mengshukeji.github.io/LuckysheetDocs/guide/#features 

I could't find any details about this, further docs and/or a demo.

**Describe the solution you'd like**
Docs and/or demo of this feature should be added if this feature is already working, the point should be marked as TODO otherwise.

**Comment by mengshukeji** [comment]
Here is the front-end parameter configuration of collaborative editing shown.

[operate](https://mengshukeji.github.io/LuckysheetDocs/guide/operate.html)

Any questions, please let us know
