### ISSUE TITLE
[temp tutorial] save&load to/from server

### ISSUE THREAD

**Issue by lofcz** [mengshukeji/Luckysheet#119]
This is my ad-hoc solution for persisting & loading sheets. I'm posting this here as several customers asked this question on gitter and there are so far to my best knowledge no official docs about this. 

You might've tried persisting result of `luckysheet.getLuckysheetfile()` and once you've loaded it back noticed that no cells were actually restored. Try to call `luckysheet.getLuckysheetfile()[0].data` and notice it's actually a huge array of mostly empty cells. As we don't need to store this bloat Luckysheet developers smartly transform this to a "patch" which they call _celldata_. All we need to do is to transform these raw data into celldata format and persist that.

Store:

```js
var currentSheet = 0; // I'm storing only the first sheet of the document, you might want to store them all, just iterate it
var rawData = luckysheet.getLuckysheetfile();
var rawCelldata = luckysheet.transToCellData(rawData[currentSheet ].data); // luckysheet.transToCellData this transforms rawData into celldata format
rawData[currentSheet].celldata = rawCelldata; // from the input json on load event, cells are read from "celldata" property
rawData[currentSheet].data = []; // dump useless data, we don't need to store this null bloat
var finalData = JSON.stringify(rawData); // fetch / $.ajax / axios / signalr ... send this to server however you do it
```

Once you want to load the sheet:

```js    
luckysheet.create({
    container: 'yourDiv',
    data: JSON.parse(`@Html.Raw(finalData)`) // <-- instead of @Html.Raw just deencode stored json, this is for .net
});
```

It would be nice if the dev team could add some official docs about this common topic. Feel free to use this now.

**Comment by mengshukeji** [comment]
Thank you very much for sharing your experience.

We also discovered this problem and provided a new API: getAllSheets
