### ISSUE TITLE
[BUG]发现了个bug

### ISSUE THREAD

**Issue by Jasperzhuangxin** [mengshukeji/Luckysheet#120]
**描述错误**
导入数据到sheet的时候，在F12中出现下面的内容。
![image](https://user-images.githubusercontent.com/19630828/97081364-9216a480-1634-11eb-8dfa-2caf9fba7478.png)

![image](https://user-images.githubusercontent.com/19630828/97081368-9a6edf80-1634-11eb-8d86-188d9d4e1a19.png)

当修改导入数据的其中一列的内容，将20201024130957改成2020-10-24 13:09:57后，则不显示错误提示。
会不会是源代码中的容错机制不完整？

**Comment by mengshukeji** [comment]
正在排查

**Comment by Dushusir** [comment]
原因是浏览器resize的时候，工具栏的DOM还没构造完成，所以宽度数据获取不到。做一个提前判定即可。
