### ISSUE TITLE
exitEditMode 没有编辑过单元格式，调用会报错

### ISSUE THREAD

**Issue by WJWM0316** [mengshukeji/Luckysheet#135]
![image](https://user-images.githubusercontent.com/24445802/97407846-3e5ad280-1936-11eb-851d-ed14c5cdd380.png)
缺少判断条件吧

**Comment by WJWM0316** [comment]
![image](https://user-images.githubusercontent.com/24445802/97408525-29cb0a00-1937-11eb-9fa4-383bde3563eb.png)

**Comment by WJWM0316** [comment]
![image](https://user-images.githubusercontent.com/24445802/97409125-18363200-1938-11eb-9b30-2cf61702d7ff.png)
加多个判断就好了

**Comment by sunc0323** [comment]
> ![image](https://user-images.githubusercontent.com/24445802/97409125-18363200-1938-11eb-9b30-2cf61702d7ff.png)
> 加多个判断就好了

你这样判断还会出现其他问题，比如编辑了一个单元格再delete清空内容，调用exitEditMode会恢复删除的内容，
![Uploading image.png…]()
我是这样改的，当处在编辑模式下才去触发退出编辑模式的逻辑

**Comment by sunc0323** [comment]
> ![image](https://user-images.githubusercontent.com/24445802/97409125-18363200-1938-11eb-9b30-2cf61702d7ff.png)
> 加多个判断就好了

你这样判断还会出现其他问题，比如编辑了一个单元格再delete清空内容，调用exitEditMode会恢复删除的内容，
![image](https://user-images.githubusercontent.com/23629147/97438338-9f4ad080-195f-11eb-979b-f970260eb370.png)
我是这样改的，当处在编辑模式下才去触发退出编辑模式的逻辑

**Comment by mengshukeji** [comment]
> > ![image](https://user-images.githubusercontent.com/24445802/97409125-18363200-1938-11eb-9b30-2cf61702d7ff.png)
> > 加多个判断就好了
> 
> 你这样判断还会出现其他问题，比如编辑了一个单元格再delete清空内容，调用exitEditMode会恢复删除的内容，
> ![image](https://user-images.githubusercontent.com/23629147/97514141-05b80900-19c9-11eb-92eb-fa8239e3f3da.png)
> 我是这样改的，当处在编辑模式下才去触发退出编辑模式的逻辑

很好的想法，帮忙直接提交PR吧

**Comment by WJWM0316** [comment]
谢谢大佬，确实是这样
