### ISSUE TITLE
[BUG]导入按https://www.cnblogs.com/DuShuSir/p/13179483.html方式报错

### ISSUE THREAD

**Issue by a564559583** [mengshukeji/Luckysheet#136]
var mask = luckysheet.mask.genarate($td.text());
Uncaught TypeError: Cannot read property 'genarate' of undefined
通过luckysheet获取不到mask

**Comment by mengshukeji** [comment]
现在导入已经有Luckexcel支持，欢迎试用反馈：

[Luckyexcel](https://github.com/mengshukeji/Luckyexcel)
