### ISSUE TITLE
设置了首行冻结之后， 鼠标滚轮 滚动无效

### ISSUE THREAD

**Issue by WJWM0316** [mengshukeji/Luckysheet#138]
设置了首行冻结之后， 鼠标滚轮 滚动无效， 拖拽滚动条正常

**Comment by WJWM0316** [comment]
官方的demo 又没出现这个bug， 但是我自己的却已设置冻结就无法滚动奇葩

**Comment by mengshukeji** [comment]
感谢反馈。还需要查查有没有其他问题。暂时先关闭issue。出现明显的问题再另开issue

**Comment by WJWM0316** [comment]
这个已经没问题了------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;mengshukeji&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月31日(星期四) 下午2:32
收件人:&nbsp;&quot;mengshukeji/Luckysheet&quot;<Luckysheet@noreply.github.com&gt;;
抄送:&nbsp;&quot;WJWM0316&quot;<429029710@QQ.COM&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mengshukeji/Luckysheet] 设置了首行冻结之后， 鼠标滚轮 滚动无效 (#138)
