### ISSUE TITLE
更新后的一些小问题

### ISSUE THREAD

**Issue by SuyongSun** [mengshukeji/Luckysheet#14]
1、设置折行显示后拖动改变列宽，该单元格内容显示不出来。
2、单元的文字垂直对齐方式问题，设置为底部对齐，不管单元格高度多少，文字总会缺失一半。（该问题似乎只在firefox下出现）
3、图表添加后无法操作，也无法通过撤销操作删除，图表会在每个sheet页显示。
4、columlen这个地方应该是个typo，定义列的部分columnlen。（第一版就有了）
5、国际化的命名上是不是按全称会更通用一些，比如使用zh_CN/en_US。
补充：
6、点击添加按钮增加sheet页后，多次执行还原撤销操作，操作后会出现重复sheet，无法还原为原始状态，且所有sheet页数据消失，同时部分菜单功能失效。

**Comment by Dushusir** [comment]
> 1、设置折行显示后拖动改变列宽，该单元格内容显示不出来。
> 2、单元的文字垂直对齐方式问题，设置为底部对齐，不管单元格高度多少，文字总会缺失一半。（该问题似乎只在firefox下出现）
> 3、图表添加后无法操作，也无法通过撤销操作删除，图表会在每个sheet页显示。
> 4、columlen这个地方应该是个typo，定义列的部分columnlen。（第一版就有了）
> 5、国际化的命名上是不是按全称会更通用一些，比如使用zh_CN/en_US。

1,2,4正在修复
3图表暂未迁移完成,后面会发布新版
5因为暂只计划中英文,所以先保持简洁,后续有更多语言计划,再商讨是否修改.

**Comment by SuyongSun** [comment]
补充：
6、增加sheet页后通过还原撤销操作，操作后会出现重复sheet，且无法还原为原始状态。

**Comment by mengshukeji** [comment]
问题1可能在老版本谷歌浏览器中存在问题，推荐升级到最新谷歌浏览器使用，浏览器兼容性问会逐步加入优化。
问题2已修复
问题3图表已允许切换页时正确的显示隐藏，支持删除操作，其中撤销重做会在后续完善
问题4已修复
问题6已修复
