### ISSUE TITLE
暴露出来的钩子函数怎么用  配置项里都没有hook怎么配置  看不太懂文档在钩子函数那一块要表达什么

### ISSUE THREAD

**Issue by liming1515** [mengshukeji/Luckysheet#140]
**描述错误**
清楚简洁地描述错误是什么。

**重现**
重现错误的步骤：
1.第一步操作
2.第二步操作
3.第三步操作
4.最后看到了什么错误

**期望的结果**
对您期望发生的结果简洁明了的描述。

**屏幕截图或演示**
方便的话，贴上屏幕截图或在线链接复现问题，我们复测时会更精准

**环境：**
  -操作系统：[例如 Windows，Mac，Linux]
  -浏览器 版本号：[例如 Chrome 版本 84.0.4147.105（正式版本） （64 位），Safari，Firefox，Edge]
  -Luckysheet版本：[例如 1.0.1，最新]

**备注**
其他说明

**Comment by mengshukeji** [comment]
钩子函数正在开发，相应案例也会跟上，稍安勿躁。欢迎后续更新。
