### ISSUE TITLE
各位大神，钩子函数能不能给点实例

### ISSUE THREAD

**Issue by jhxg** [mengshukeji/Luckysheet#150]
各位大神，钩子函数能不能给点实例

**Comment by jhxg** [comment]
各位大神，钩子函数能不能给点实例

**Comment by pengyonglei** [comment]
![image](https://user-images.githubusercontent.com/11027128/97955853-32618b80-1de2-11eb-9393-0a54b81e0087.png)
人家的index.htmll里面就已经写好了demo, 你可以看看

**Comment by pengyonglei** [comment]
放在 options.hook 下面

**Comment by mengshukeji** [comment]
> 放在 options.hook 下面

感谢分享经验
