### ISSUE TITLE
我刚开始 看文档很懵吖

### ISSUE THREAD

**Issue by jws2001** [mengshukeji/Luckysheet#156]
**您的功能请求与问题有关吗？**
清楚简洁地说明问题。

**描述您想要的解决方案**
对您想要的功能效果简洁明了的描述。

**其他内容**
其他说明

**Comment by mengshukeji** [comment]
收到您的反馈，我们会继续优化文档和代码，尽全力做好这个插件。

如果有具体疑问，请另外开issue
