### ISSUE TITLE
表格操作通过updateUrl回传的一些问题汇总

### ISSUE THREAD

**Issue by pengyonglei** [mengshukeji/Luckysheet#159]
1. 设置【字体大小】, 会回传一个 all 的消息.

2. 设置了一个区域的边框, updateUrl回传回来的时候, 会把整个sheet所有的边框信息都回传.

3. 设置【换行方式】会先回传一个 all 的信息

**Comment by mengshukeji** [comment]
'all'类型也是内部区分操作类型用的允许的参数，在没有bug的情况下旧参数不建议改动，因为需要改后端和其他开源后端的接口。


新的操作类型，会做细致归类。
