### ISSUE TITLE
[BUG]横向滑动到末端触发纵向滚动

### ISSUE THREAD

**Issue by mongris** [mengshukeji/Luckysheet#16]
**Describe the bug**
未选中单元格时，用MacBook自带trackpad来横向滑动（从左往右），当滑动到末端，纵向滚动条也会发生滑动

**To Reproduce**
打开 demo 站点，增加页面的rows，在页面同时出现XY轴的滚动条后，用trackpad来滑动页面

**What is expected?**
横向（或纵向）的滑动，不会触发纵向（或横向）的滚动

**Environment**
 - OS: Mac
 - Browser: Safari
 - Luckysheet Version: latest

**Comment by wbfsa** [comment]
最近更新了一版，还没有上到demo里，请今天再看看
