### ISSUE TITLE
[Feature request]I have an idea for cell lock

### ISSUE THREAD

**Issue by jianyi0115** [mengshukeji/Luckysheet#17]
打算用这个控件实现复杂报表的填报。目前无法实现控制哪些单元格允许编辑，哪些单元格只读。
比如，固定文本类的cell和公式cell只读。

如果通过扩展开发的方式，目前的接口能做到吗？比如cell focus触发一个事件，事件里判断是否允许编辑这个cell？

**Comment by wbfsa** [comment]
api，回调函数以及方法正在整理和开放中，有需要可以提出，如比较复杂可以加群

**Comment by mengshukeji** [comment]
> 打算用这个控件实现复杂报表的填报。目前无法实现控制哪些单元格允许编辑，哪些单元格只读。
> 比如，固定文本类的cell和公式cell只读。
> 
> 如果通过扩展开发的方式，目前的接口能做到吗？比如cell focus触发一个事件，事件里判断是否允许编辑这个cell？

**Comment by mengshukeji** [comment]
> 打算用这个控件实现复杂报表的填报。目前无法实现控制哪些单元格允许编辑，哪些单元格只读。
> 比如，固定文本类的cell和公式cell只读。
> 
> 如果通过扩展开发的方式，目前的接口能做到吗？比如cell focus触发一个事件，事件里判断是否允许编辑这个cell？

会在单元格格式中增加一个配置 ‘ae’，是否允许编辑此单元格，已经列入开发计划，有详细需求，可以添加Luckysheet官方小编微信详细沟通（vx: dushusir2）

**Comment by cdswyda** [comment]
> > 打算用这个控件实现复杂报表的填报。目前无法实现控制哪些单元格允许编辑，哪些单元格只读。
> > 比如，固定文本类的cell和公式cell只读。
> > 如果通过扩展开发的方式，目前的接口能做到吗？比如cell focus触发一个事件，事件里判断是否允许编辑这个cell？
> 
> 会在单元格格式中增加一个配置 ‘ae’，是否允许编辑此单元格，已经列入开发计划，有详细需求，可以添加Luckysheet官方小编微信详细沟通（vx: dushusir2）

这块有进展了吗？ 最新的文档上还没发现 `ae` 相关的描述

**Comment by Haowensheng** [comment]
想问一下这个单元格可编辑现在有了吗
