### ISSUE TITLE
[BUG]使用setCellValue设置单元格的背景色为transparent，会隐藏右边线和下边线

### ISSUE THREAD

**Issue by YasuoHub** [mengshukeji/Luckysheet#173]
**描述错误**
使用setCellValue设置单元格的背景色为transparent，会同时隐藏右边线和下边线，但是我的本来目的只是想将单元格的背景颜色去掉。

**重现**
重现错误的步骤：
1.第一步操作
luckysheet.setCellValue(1, 1, {bg: 'transparent'})
2.第二步操作
3.第三步操作
4.最后看到了什么错误
同时隐藏右边线和下边线
**期望的结果**
我希望能直接清除单元格背景颜色。
或者提供一下工具栏中的重置颜色的API

**备注**
其他说明

**Comment by wpxp123456** [comment]
用 setCellFormat 或者 luckysheet.setCellValue(1, 1, {bg: null})
