### ISSUE TITLE
如何在vue或者react项目中使用

### ISSUE THREAD

**Issue by nishizhenfengge** [mengshukeji/Luckysheet#19]
什么时候会出vue和react的版本呢

**Comment by wbfsa** [comment]
https://github.com/Dushusir/vue-demo

接入vue参考下？ 等功能都做完了才会考虑出vue react angular版本

**Comment by danielcai1987** [comment]
@nishizhenfengge React中使用的例子也有了 https://github.com/mengshukeji/luckysheet-react
