### ISSUE TITLE
[Feature Request] Suggestions !#zh: 小建议

### ISSUE THREAD

**Issue by ly525** [mengshukeji/Luckysheet#2]
- [x] please add License file to the project

- [ ] please use commit cz to standardize the commit message

- [ ] please clear up the src/luckysheet-core.js 

!#zh: 
- [ ] 请添加 license 文件，表明项目的开源协议

- [ ]  请使用类似 commit cz 之类的工具，规范 commit message

- [ ] 请整理 src/luckysheet-core.js 代码

**Comment by liuyang3688** [comment]
luckysheet-core.js 单文件确实太大了 源码读上去也费尽 抽时间优化吧

**Comment by mengshukeji** [comment]
感谢建议。
license 、 commit、模块化下一版本会改进和推出
