### ISSUE TITLE
合并单元格报错

### ISSUE THREAD

**Issue by mydogger** [mengshukeji/Luckysheet#20]
plugin.js:1 Uncaught TypeError: ((O.event.special[o.origType] || {}).handle || o.handler).apply is not a function
    at HTMLDivElement.dispatch (plugin.js:1)
    at HTMLDivElement.b.handle (plugin.js:1)

**Comment by wbfsa** [comment]
这个不是合并单元格的错误，图表插件报错，不影响功能的正常使用，之后会修复

**Comment by mengshukeji** [comment]
已修复
