### ISSUE TITLE
[BUG]关于冻结行列滚动条问题

### ISSUE THREAD

**Issue by morningsun42** [mengshukeji/Luckysheet#203]
**Describe the bug**
情况1、冻结行列到选区以后，如果滚动条移动了，再执行一次冻结，滚动条无法滚回最左或最顶。
情况2、滚动条不在最左或者最上的位置，执行冻结行列，滚动条无法滚回最左或最顶

**Screenshots or demo**
<img width="473" alt="WX20201111-102358@2x" src="https://user-images.githubusercontent.com/40629010/98758056-d1047280-2408-11eb-84a0-44201fca20d3.png">

**Environment**
 - OS: [e.g. Windows,Mac,Linux]
 - Browser Version: [e.g. Chrome Version 84.0.4147.105 (Official Build) (64-bit), Safari,Firefox,Edge]
 - Luckysheet Version: [e.g. 1.0.1,latest]

**Additional context**

**Comment by wpxp123456** [comment]
我们现在的冻结设计就是这样  冻结的时候是看滚动的  滚动的部分也会被冻结掉  不然你想 如果能滚动上去 其实上面一块滚动区域都得撑开了  你真不需要可以取消滚动后  再去设置你想要的那种

**Comment by wpxp123456** [comment]
取消冻结  打错了
