### ISSUE TITLE
[BUG]协同编辑：高亮框未跟随缩放

### ISSUE THREAD

**Issue by mengshukeji** [mengshukeji/Luckysheet#209]
**描述错误**
高亮框未跟随缩放

**重现**
重现错误的步骤：
协同编辑的时候，当有其他用户在编辑的时候，缩放本工作表，高亮框未跟随缩放

**期望的结果**
高亮框应跟随缩放

**屏幕截图或演示**
![image](https://user-images.githubusercontent.com/61444807/98783182-1c804600-2434-11eb-8d2f-f93676c67ba0.png)

**环境：**
- 操作系统： Windows
- 浏览器 版本号： Edge 版本 86.0.622.58 (官方内部版本) (64 位)
- Luckysheet版本： 最新

**Comment by renxxing** [comment]
Duplicate of #207
