### ISSUE TITLE
[BUG] 表格行数设置大于 20000，表格内滑动鼠标滚轮会造成页面卡死

### ISSUE THREAD

**Issue by Miachol** [mengshukeji/Luckysheet#22]
我尝试设置行数为 15000 时表格滑动速度相比于几十行要慢。当设置为 20000 行时，表格内滑动滚轮会造成整个页面卡死，但是我用鼠标点击右侧滚动条是可以正常下滚的，而不会造成卡死。

有人遇到过相同的问题吗？

**Comment by wbfsa** [comment]
是的，鼠标滚轮算法有问题，我们尽快调整

**Comment by wbfsa** [comment]
请验证一下
