### ISSUE TITLE
[BUG]协同编辑：多人编辑存在数据丢失

### ISSUE THREAD

**Issue by airclear** [mengshukeji/Luckysheet#220]
**描述错误**
多人编辑存在数据丢失

**重现**
开两个窗口，第一个人编辑了，第二个人再编辑，然后第一个人再编辑一下，发现第一个人之前编辑的丢失了

**期望的结果**
数据不丢失

**Comment by oy-paddy** [comment]
是覆盖了单个单元格还是整个sheet？单个单元格的数据丢失，还是整体编辑的数据丢失？

**Comment by airclear** [comment]
单元格数据丢失
