### ISSUE TITLE
[BUG]最小行数与列数

### ISSUE THREAD

**Issue by SuyongSun** [mengshukeji/Luckysheet#23]
**描述错误**
LuckySheet在构建时代码中设置了最小行数为30，最小列数为22，实际中希望按实际的行列数生成表格。

**重现**
初始化时给的行列数小于30、22，LuckySheet会以默认的行列数创建。

**期望的结果**
1、这两个值是否有特殊的意义的？如无，可以不必限制，或限制得更小一些。
2、表格是否可以提供每个sheet中有效的数据范围，即每个sheet中的有效数据行列数，对于完全无内容或无格式设置的行列可以排除在外。

**Comment by liuyang3688** [comment]
这个我改过一版 抽空可以分享你

**Comment by wbfsa** [comment]
可以使用sheet的row和column设置行列数量，已经修复
