### ISSUE TITLE
[Feature request]Remove eval()

### ISSUE THREAD

**Issue by mengshukeji** [mengshukeji/Luckysheet#237]
**Is your feature request related to a problem? Please describe.**
When npm run dev or npm run build, the console will report eval warning, which does not affect the operation, but affects the development experience, you can refer to
https://github.com/feathersjs/feathers/issues/588

**Comment by flowerField** [comment]
@I can solve it

**Comment by flowerField** [comment]
[Feature request]Remove eval() #237

In short, the solution to delete Eval is as follows: Using the new function syntax feature.
Sample processing：
1、Data analysis
` let data = eval('(' + result.data + ')');`
for
`let data = new Function("return " + result.data )();`

2、Involving the execution of functions
`eval('data.splice(' + st_i + ', 0, ' + arr.join(",") + ')');`
for
`new Function("return " + 'data.splice(' + st_i + ', 0, ' + arr.join(",") + ')')();`

**Comment by mengshukeji** [comment]
Great solution!
