### ISSUE TITLE
[BUG]粘贴单元格时，公式栏的内容始终是上次在单元格输入的内容，而不是复制的内容

### ISSUE THREAD

**Issue by laixstx** [mengshukeji/Luckysheet#25]
**描述错误**
粘贴单元格时，公式栏的内容始终是上次在单元格输入的内容，而不是复制的内容

**重现**
重现错误的步骤：
①先任意复制一份文本，比如复制“2333”；
②在任意单元格输入内容，比如输入“123”；
③选择其他单元格，粘贴。
此时，会发现公式栏的内容是“123”，即上次在单元格输入的内容，而不是复制的内容“2333”

**期望的结果**
粘贴单元格时，公式栏显示的内容应该是真实复制的内容

**屏幕截图或演示**
![image](https://user-images.githubusercontent.com/10735940/92069327-a0d29f00-eddb-11ea-819c-47fc652dc739.png)

**环境：**
  -操作系统：win10 专业版
  -浏览器 版本号：Chrome 版本 79.0.3945.88（正式版本） （64 位）、QQ浏览器最新版
  -Luckysheet版本：最新

**Comment by wbfsa** [comment]
已经修复
