### ISSUE TITLE
[Feature request]Open: range to coordinate api

### ISSUE THREAD

**Issue by mengshukeji** [mengshukeji/Luckysheet#251]
**Is your feature request related to a problem? Please describe.**
What I get through API: luckysheet.getRange() is the number of visit rows and columns of the current selection, `{column: [0, 1],
row: [0, 1]}`

But I want to get something like `A1:B2`

**Describe the solution you'd like**
Open: range to coordinate api

**Comment by flowerField** [comment]
Several schemes are given for reference. If there is a suitable one, code implementation is carried out.

Scheme 1: add the field axis to the selected area. The field type is string, and the value form is "A1" or "C1: C3".

Current returned data structure:
 ```javascript
 [{"row":[0,7],"column":[0,0]},{"row":[0,2],"column":[2,2]},{"row":[4,4],"column":[3,3]},{"row":[8,10],"column":[2,4]}]
 ```

Data structure returned after adjustment：
 ```javascript
 [{"row":[0,7],"column":[0,0],axis:"A1:A8"},{"row":[0,2],"column":[2,2],axis:"C1:C3"},{"row":[4,4],"column":[3,3],axis:"D5"},{"row":[8,10],"column":[2,4],axis:"C9:E11"}]
 ```

**Comment by flowerField** [comment]
Scheme 2: replace row and column data with axis field data
Current returned data structure:
```json
[{"row":[0,7],"column":[0,0]},{"row":[0,2],"column":[2,2]},{"row":[4,4],"column":[3,3]},{"row":[8,10],"column":[2,4]}]
```
Data structure returned after adjustment：
["A1:A8","C1:C3","D5","C9:E11"]

Of course, we can also consider adding the getRangeAxis API on the basis of retaining the original API, which returns the data of the above structure.

**Comment by flowerField** [comment]
@I can solve it

**Comment by mengshukeji** [comment]
Great solution!
