### ISSUE TITLE
[BUG]撤销操作之后，单元格选框不见了

### ISSUE THREAD

**Issue by laixstx** [mengshukeji/Luckysheet#26]
**描述错误**
撤销操作之后，单元格选框不见了

**重现**
重现错误的步骤：
1、修改任意单元格，然后"撤销”

**期望的结果**
撤销操作之后，单元格选框应该定位到撤销的单元格，与 excel 一致。

**屏幕截图或演示**
![image](https://user-images.githubusercontent.com/10735940/92069544-353d0180-eddc-11ea-882b-9f744b335c65.png)
![image](https://user-images.githubusercontent.com/10735940/92069561-3bcb7900-eddc-11ea-8043-48de6c149539.png)

**环境：**
  -操作系统：win10
  -浏览器 版本号：Chrome 版本 79.0.3945.88（正式版本） （64 位）
  -Luckysheet版本：最新

**Comment by wbfsa** [comment]
好的 尽快修复
