### ISSUE TITLE
[BUG]Find a bug

### ISSUE THREAD

**Issue by acehoe** [mengshukeji/Luckysheet#265]
**Describe the bug**
数据表中有浮点数据，精确到小数点后2位。对此数据创建数据透视表，比如做简单的求和，数据会被四舍五入。比如原来数据表中数据为123.45，在数据透视表中则会变为123.5。在数据透视表中修改精度，此数据则会变为123.50。无法恢复到原来的精度。

**To Reproduce**
1. 创建一个sheet，添加两列数据如下：
       A      B
     ww   123.45
     ee    1.33
2. 针对上述两列数据创建数据透视表，数据透视表中，A列为行，B列为数值。在数值列设置为求和。
3. 此时可以看到两列数据变为了：
      ee     1.3
      ww   123.5
4. 此时若修改第二列数据的精度，则只会在数值后添加0. 比如修改数据透视表中第二列数据格式为数字(精确到小数点后2位)。此时只会在小数点后加0：

     ee     1.30
     ww   123.50

**What is expected?**
希望在创建数据透视表的时候可以不要四舍五入，或者可以设置保留精度的位数。

**Screenshots or demo**
数据表截图：
![Screen Shot 2020-11-23 at 7 33 17 PM](https://user-images.githubusercontent.com/65149986/99957638-fe66fe00-2dc2-11eb-8834-fe487331277a.png)
数据透视表截图：
![Screen Shot 2020-11-23 at 7 33 37 PM](https://user-images.githubusercontent.com/65149986/99957670-0a52c000-2dc3-11eb-8423-3082af5fcfa6.png)
修改精度后的数据透视表jie tu截图：
![Screen Shot 2020-11-23 at 7 33 58 PM](https://user-images.githubusercontent.com/65149986/99957702-16d71880-2dc3-11eb-9c6a-3f47bb80277b.png)

**Environment**
 - OS: [Mac,Linux]
 - Browser Version: [e.g. Chrome Version 84.0.4147.105 (Official Build) (64-bit), Safari,Firefox,Edge]
 - Luckysheet Version: [e.g. 1.0.1,latest]

**Comment by wpxp123456** [comment]
数据透视表 这边现在的数字格式 是 小于1 精度是小数点后6位  大于1 精度是小数点后1位   
如果不符合你的使用要求 可以二开修改下
在pivotTable.js  addStatisticsData里面 let num = numFormat(d_value)这块
