### ISSUE TITLE
[BUG] 删除整行websocket一直下发消息

### ISSUE THREAD

**Issue by airclear** [mengshukeji/Luckysheet#275]
**描述错误**
删除整行websocket一直下发消息，死循环好像

**重现**
重现错误的步骤：
1.打开chrome的network面板，ws子面板
2.打开协作demo
3.删除一行

**期望的结果**
不死循环下发消息

**Comment by wpxp123456** [comment]
删除行列操作会影响很多配置  筛选配置、条件格式配置、交替颜色配置、数据验证配置等等  一次操作  发送很多配置改变到服务端 然后返回的那个是服务端给的操作成功返回 前端不做处理的
