### ISSUE TITLE
luckysheet.config()没有title这个值，求大大补上

### ISSUE THREAD

**Issue by lewis828** [mengshukeji/Luckysheet#279]
**luckysheet.config()没有title这个值，求大大补上**

**Comment by mengshukeji** [comment]
> **luckysheet.config()没有title这个值，求大大补上**

luckysheet.config()好像没有这个API。

您是指luckysheet.create()嘛，这个是有title的。
然后还有一个luckysheet.toJson()也可以获取初始化的配置信息。

**Comment by lewis828** [comment]
> > **luckysheet.config()没有title这个值，求大大补上**
> 
> luckysheet.config()好像没有这个API。
> 
> 您是指luckysheet.create()嘛，这个是有title的。
> 然后还有一个luckysheet.toJson()也可以获取初始化的配置信息。

不是的，我是指sheet**修改后**title的值，注意是**修改后**
而不是初始化的值
luckysheet.create()里面的title只是初始化的值……

**Comment by lewis828** [comment]
> > **luckysheet.config()没有title这个值，求大大补上**
> 
> luckysheet.config()好像没有这个API。
> 
> 您是指luckysheet.create()嘛，这个是有title的。
> 然后还有一个luckysheet.toJson()也可以获取初始化的配置信息。

![image](https://user-images.githubusercontent.com/35283915/100840657-2e905a00-34b1-11eb-955a-aa4694571726.png)
贴图解释给您听吧，我编辑完，获取不了更新后的title~~

**Comment by mengshukeji** [comment]
> > > **luckysheet.config()没有title这个值，求大大补上**
> > 
> > 
> > luckysheet.config()好像没有这个API。
> > 您是指luckysheet.create()嘛，这个是有title的。
> > 然后还有一个luckysheet.toJson()也可以获取初始化的配置信息。
> 
> ![image](https://user-images.githubusercontent.com/35283915/100840657-2e905a00-34b1-11eb-955a-aa4694571726.png)
> 贴图解释给您听吧，我编辑完，获取不了更新后的title~~

群里回复过了哈，这里也贴一下，给不知道的朋友参考，两种方法：

1. `document.querySelector('.luckysheet_info_detail_input').value`
2. `luckysheet.toJson().title`
