### ISSUE TITLE
[Feature request] Support for locked cells and hidden formulas

### ISSUE THREAD

**Issue by phtj** [mengshukeji/Luckysheet#28]
Similar to excel, cells could be set to be `locked` and/or `hidden`, 

- For locked cells, formulas and values would not be editable...
- For hidden cells, formulas would not be visible

For a cell with a formula, if you lock it and hide it, then you would not be able to edit it, and you would not be able to see the formula. You would only be able to see the result of the formula being executed.

**Comment by wbfsa** [comment]
OK, it add to plan

**Comment by wbfsa** [comment]
Already supported
