### ISSUE TITLE
[BUG]Find a bug

### ISSUE THREAD

**Issue by blissleek** [mengshukeji/Luckysheet#282]
前端小白 在集成到vue时报这个错，单元格也无法点击，求大佬解答 
jquery.js?eedf:4055 Uncaught TypeError: $(...).mousewheel is not a function

**Comment by TheaWu7** [comment]
> 前端小白 在集成到vue时报这个错，单元格也无法点击，求大佬解答 jquery.js?eedf:4055 Uncaught TypeError: $(...).mousewheel is not a function

请问是怎么解决的呢，我也遇到这个问题了
