### ISSUE TITLE
[BUG]先双击日期类型的单元格打开日期选择器，之后换到别的类型单元格双击进入编辑状态，再单击输入框，仍然会弹出日期选择器

### ISSUE THREAD

**Issue by wangyinhe** [mengshukeji/Luckysheet#286]
先双击日期类型的单元格打开日期选择器，然后换到别的类型单元格双击进入编辑状态，再单击输入框，仍然会弹出日期选择器

**Comment by mengshukeji** [comment]
> 先双击日期类型的单元格打开日期选择器，然后换到别的类型单元格双击进入编辑状态，再单击输入框，仍然会弹出日期选择器

本地没有复现，请帮忙描述再详细一点：

先双击日期类型的单元格打开日期选择器，然后换到别的类型单元格双击进入编辑状态，再单击输入框（哪个输入框），仍然会弹出日期选择器

**Comment by wangyinhe** [comment]
新的服务已经没有问题了
