### ISSUE TITLE
[BUG]  复制粘贴单元格之后字体变了

### ISSUE THREAD

**Issue by javahuang** [mengshukeji/Luckysheet#29]
**Describe the bug**
单元格复制粘贴之后字体发生了变化

**To Reproduce**
1. 复制一个单元格
2. 切换到另外一个单元格输入
3. 再切换一个单元格粘贴
4. 粘贴后的字体和第二步复制的字体大小不一致，另外按 command 键，会在公式栏显示之前复制的值

**What is expected?**
由 [css length](https://developer.mozilla.org/en-US/docs/Web/CSS/length) 文档可知，1in = 2.54cm = 96px，1pt = 1/72nd of 1in. 所以 px 可以直接换算成 pt，和设备的 dpr 是没有关系的。

**Screenshots or demo**
![1222](https://user-images.githubusercontent.com/3992393/92444835-052f9d00-f1e6-11ea-9c48-9c50e4701e04.gif)

**Environment**
 - OS: Mac
 - Browser Version:  Chrome Version 85.0.4183.83 (Official Build) (64-bit),Chrome
 - Luckysheet Version: latest

**Additional context**

**Comment by Dushusir** [comment]
copy text will get origin font family
