### ISSUE TITLE
[BUG]userInfo配置不生效

### ISSUE THREAD

**Issue by linen1794** [mengshukeji/Luckysheet#290]
官网代码：https://github.com/mengshukeji/Luckysheet/tree/v2.1.7

![image](https://user-images.githubusercontent.com/30710337/100858853-79b66700-34c9-11eb-977a-7ef56885f875.png)

![image](https://user-images.githubusercontent.com/30710337/100859048-b7b38b00-34c9-11eb-9e58-b2d2eb348c44.png)

**环境：**
  -操作系统：MacOs Catalina 10.15.7
  -浏览器 版本号：Google Chrome 版本 87.0.4280.67（正式版本） (x86_64)
  -Luckysheet版本：2.1.7

**Comment by mengshukeji** [comment]
Duplicate of #291
