### ISSUE TITLE
[Feature Requst] switch scrollbar color and background color !#zh: 互换滚动条的 color与background-color

### ISSUE THREAD

**Issue by ly525** [mengshukeji/Luckysheet#3]
request：can  you  please switch scrollbar color and background color

!#zh: 
遇到的问题：
滚动条白色和主体内容颜色一致，非常容易混淆

期待
UI 建议:是否可以 滚动条采用灰色, 滚动条背景色采用白色

截图：
![image](https://user-images.githubusercontent.com/12668546/84566442-c08d9480-ada3-11ea-9e12-0a8624b892dc.png)

腾讯文档：
![image](https://user-images.githubusercontent.com/12668546/84566494-29750c80-ada4-11ea-95d7-eedc262d6496.png)

**Comment by mengshukeji** [comment]
感谢建议，整体样式部分会借鉴腾讯文档做体验改进

**Comment by wbfsa** [comment]
已经改进
