### ISSUE TITLE
[BUG]CDN引入的时候一直报jQuery的问题

### ISSUE THREAD

**Issue by heyouquan** [mengshukeji/Luckysheet#310]
**描述错误**
在通过CDN引入到React项目中，一直报JQuery的错误
**重现**
重现错误的步骤：
1.第一步操作
在HTML文件中引入
![image](https://user-images.githubusercontent.com/29010781/101447542-63445b80-3960-11eb-9ccd-9d10eecd5779.png)

4.最后一直报这个错误
![image](https://user-images.githubusercontent.com/29010781/101447671-a43c7000-3960-11eb-807e-4d2041deaeb5.png)

**环境：**
  -操作系统：[Mac]
  -浏览器 版本号：[例如 Chrome 版本 84.0.4147.105（正式版本） （64 位）]
  -Luckysheet版本：[最新]

**Comment by cxmrf** [comment]
单独引入jquery就行了

**Comment by heyouquan** [comment]
> 单独引入jquery就行了

这个问题也是因为没有挂载$和jQuery到window对象上，gulp打包的这些依赖都没有挂载到window上，有什么好的办法快速解决吗？
![image](https://user-images.githubusercontent.com/29010781/101902115-15905300-3bed-11eb-998d-779cc5b80112.png)

**Comment by mengshukeji** [comment]
1. 先检查是否和本地项目的jQuery项目冲突
2. 参考 [Luckysheet-react](https://github.com/mengshukeji/Luckysheet-react)

还有问题再reopen吧

**Comment by linpeinan** [comment]
> > 约会引入jquery就行了
> 
> 这个问题也是因为没有挂载$和jQuery到窗口对象上，gulp打包的这些依赖都没有挂载到窗口上，有什么好的办法快速解决吗？
> ![图片](https://user-images.githubusercontent.com/29010781/101902115-15905300-3bed-11eb-998d-779cc5b80112.png)

请问是怎么引入
