### ISSUE TITLE
用golang后端，发现不能正确接收pako.gzip后的数据

### ISSUE THREAD

**Issue by qflash** [mengshukeji/Luckysheet#311]
表现为 前端发送的数据长度和后端接收到的数据长度不一致。

临时解决办法：
pako.gzip后，再btoa转换一下，然后才发送给GOLANG后端，后端先base64解码后数据正常。

**Comment by qflash** [comment]
找到问题点了，JS是用UTF16编码，而GO用了UTF8来编码，所以GOLANG后端接收到数据后要转换一下转换为UTF16格式，然后才能解压缩不出错。
提供一个转换函数，可以用，但是不好，供以后的人参考
const (
	replacementChar = '\uFFFD'     // Unicode replacement character
	maxRune         = '\U0010FFFF' // Maximum valid Unicode code point.

	// 0xd800-0xdc00 encodes the high 10 bits of a pair.
	// 0xdc00-0xe000 encodes the low 10 bits of a pair.
	// the value is those 20 bits plus 0x10000.
	surr1 = 0xd800
	surr2 = 0xdc00
	surr3 = 0xe000

	surrSelf = 0x10000
)

func encodeStringToUTF16(s string) []byte {
	n := 0
	for _, v := range s {
		n++
		if v >= 0x10000 {
			n++
		}
	}

	a := make([]byte, n)
	n = 0
	for _, v := range s {
		switch {
		case 0 <= v && v < surr1, surr3 <= v && v < surrSelf:
			// normal rune
			a[n] = byte(v)
			n++
		case surrSelf <= v && v <= maxRune:
			// needs surrogate sequence
			r1, r2 := utf16.EncodeRune(v)
			a[n] = byte(r1)
			a[n+1] = byte(r2)
			n += 2
		}
	}
	return a[:n]
}

**Comment by unmurphy** [comment]
@qflash 你好，我这边也用的go，按照你贴的方法，发现还是没办法解析数据，能麻烦加个好友请教一下么？

**Comment by qflash** [comment]
不会吧，加上了编码转化也报invalide header错误？我的加上了就正常了哟，你看我的代码
               n, _ := websocketnow.Read(msg)
		if n == 0 {
			return
		}
		if n == 3 && string(msg[0:3]) == "rub" { //心跳
			continue
		}
decodeBytes := encodeStringToUTF16(string(msg[0:n]))
fmt.Println(decodeBytes)
reader, err := gzip.NewReader(bytes.NewReader(decodeBytes))

**Comment by unmurphy** [comment]
嗯嗯，抱歉，可以了～～ you save my life

**Comment by mengshukeji** [comment]
非常感谢分享开发经验
