### ISSUE TITLE
工具栏中英文切换

### ISSUE THREAD

**Issue by 2447382228** [mengshukeji/Luckysheet#315]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Additional context**

**Comment by mengshukeji** [comment]
收到。
Duplicate of #318

**Comment by 2447382228** [comment]
> **您的功能请求是否与问题有关？请描述。**
> 对问题的清楚简洁的描述。
> 点击中英文两个按钮，工具栏中英切换
> **描述您想要的解决方案**
> 简明扼要地描述您要发生的事情。
> changlang('zh')我用着没有用
> **其他上下文**
> 在此处添加有关功能请求的其他任何上下文或屏幕截图。

**Comment by 2447382228** [comment]
> **您的功能请求是否与问题有关？请描述。**
> 对问题的清楚简洁的描述。
> 我点击中英文按钮，工具栏切换中英文
> **描述您想要的解决方案**
> 简明扼要地描述您要发生的事情。
> 我在中文点击事件里面弄了changLang（‘zh’）;没有用
> **其他上下文**
> 在此处添加有关功能请求的其他任何上下文或屏幕截图。

**Comment by 2447382228** [comment]
> 收到。[＃318的](https://github.com/mengshukeji/Luckysheet/issues/318)
> 重复项[](https://github.com/mengshukeji/Luckysheet/issues/318)

这个api什么时候可以用呀

**Comment by Dushusir** [comment]
API changLang()已实现
