### ISSUE TITLE
[Feature request]开放切换语言的API

### ISSUE THREAD

**Issue by mengshukeji** [mengshukeji/Luckysheet#318]
**您的功能请求与问题有关吗？**
为何需要，客户提出问题，现在想实现切换语言功能，只能destory后重新create初始化，但是destory有问题，所以create换个语言配置初始化并不成功。我们讨论看来，可以直接抽象出一个切换语言的需求来做。

**描述您想要的解决方案**
开放API：
changLang('zh')
传入目标语言，切换到对应的语言界面

**其他内容**
实现方案参考：内部机制等于是需要拿到‘zh’，重新绘制表格，等于还是拿现有的表格数据重新走一遍create方法
整理流程类似于：先toJson()拿到所有表格数据，再destory表格，再create表格。

**Comment by 2447382228** [comment]
> **您的功能请求与问题有关吗？**
> 为何需要，客户提出问题，现在想实现切换语言功能，只能destory后重新create初始化，但是destory有问题，所以create换个语言配置初始化并不成功。我们讨论看来，可以直接抽象出一个切换语言的需求来做。
> 
> **描述您想要的解决方案**
> 开放API：
> changLang('zh')
> 传入目标语言，切换到对应的语言界面
> 
> **其他内容**
> 实现方案参考：内部机制等于是需要拿到‘zh’，重新绘制表格，等于还是拿现有的表格数据重新走一遍create方法
> 整理流程类似于：先toJson()拿到所有表格数据，再destory表格，再create表格。

我不要从新在新建一个表格
