### ISSUE TITLE
[Feature request]setCellValue方法允许用户添加自定义属性

### ISSUE THREAD

**Issue by xiangcaozhu** [mengshukeji/Luckysheet#320]
**您的功能请求与问题有关吗？**
在使用setCellValue()时自定义属性会被formatList过滤

**描述您想要的解决方案**
允许setCellValue()添加自有属性，或开放特定的一个字段让用户保存：例如：dc是自定义的属性对象
window['luckysheet'].setCellValue(currentData.row[0], currentData.column[0], {
     dc: {
          dicId:  record.id，
          key: record.key,
          name: record.name,
          type: record.type,
          source: record.source,
          placeholder: defaultCell.v || record.placeholder,
          selected: {}
     },
      v: 454545
})
**其他内容**
环境：
-操作系统：Window
-浏览器 版本号：chrome
-Luckysheet版本：最新

**Comment by jerry-f** [comment]
目前该 API 已经支持用户添加自定义属性，请试用

**Comment by jerry-f** [comment]
该问题已解决
