### ISSUE TITLE
luckysheet表格的左边不可以有其他元素，否则将导致luckysheet的工具栏不显示

### ISSUE THREAD

**Issue by Ezr1al** [mengshukeji/Luckysheet#321]
在初始化luckysheet的时候，需要提供一个id为luckysheet的div作为容器，如果在这个div的左边有其他的div，那么将导致luckysheet的工具栏不显示，具体如下：
![image](https://user-images.githubusercontent.com/36941749/101596056-5f333f00-3a2f-11eb-8d9b-ea907606b9a4.png)
如果其他div在id为luckysheet的div的右侧，则是显示正常的
![image](https://user-images.githubusercontent.com/36941749/101596114-7d993a80-3a2f-11eb-97ee-f9ef13c564bd.png)

**Comment by cxmrf** [comment]
原因是resize.js -> luckysheetsizeauto方法中计算超出显示范围元素时是直接使用container的宽度比对工具栏item元素offset.left。

解决方案也相对简单
![image](https://user-images.githubusercontent.com/23873153/101786865-6ba3be80-3b39-11eb-9e1f-8f4b983a64cc.png)
