### ISSUE TITLE
打包后的文件大小过大问题

### ISSUE THREAD

**Issue by gaoshuze** [mengshukeji/Luckysheet#322]
通过本地打包出来的luckysheet.umd.js有6M，而官网示例中的该文件仅有500+k，请问打包需要什么特殊处理吗？？
命令：yarn build
node : v12.18.4
npm : 6.14.6
yarn : 1.21.1
操作系统 : win10
版本 ： 2.1.5

**Comment by NoneDay** [comment]
这是因为启用了gzip 压缩。不过他真的是太大了。首次加载呈现至少要1秒以上，能明显看到loading ，真的是不爽

**Comment by mengshukeji** [comment]
关注 Duplicate of #240
