### ISSUE TITLE
[BUG]发现了个bug数字格式化报错

### ISSUE THREAD

**Issue by heyouquan** [mengshukeji/Luckysheet#327]
**描述错误**
![image](https://user-images.githubusercontent.com/29010781/101740685-21541a80-3b04-11eb-8db0-a4059b9c0309.png)

**环境：**
  -操作系统：[Windows，Mac，Linux]
  -浏览器 版本号：[Chrome 版本 84.0.4147.105（正式版本） （64 位），Safari，Firefox，Edge]
  -Luckysheet版本：[最新]
备注：通过CDN引入最新的包

**Comment by flowerField** [comment]
请检查是否引入了必要的插件。
```javascript
//引入参考
<script src="./plugins/js/plugin.js"></script>
```
format.js文件1919行使用到的numeral方法由 /Luckysheet/src/plugins/js/numeral.js文件提供，会被打包到plugin.js文件中。
