### ISSUE TITLE
[BUG]setSheetDelete时有个bug

### ISSUE THREAD

**Issue by cxmrf** [mengshukeji/Luckysheet#329]
**描述错误**
当showsheetbarConfig.sheet = false时，调用setSheetDelete会报错。

原因是#luckysheet-sheet-container被隐藏，jquery无法找到下一个可视的luckysheet-sheets-item元素，导致调用changeSheet方法时index参数为undefined，luckysheetfile中无法通过该index找到对应元素的data属性出现的问题。

该问题在隐藏sheet时理论上一样会出现。

解决方案是在setSheetHide函数中对showsheetbarConfig.sheet === false情况进行处理，
可直接通过Store.luckysheetfile.findIndex(x => !x.hide)获取下一个可视元素

**Comment by flowerField** [comment]
感谢建议！
