### ISSUE TITLE
[BUG]plugins插件加载不了

### ISSUE THREAD

**Issue by heyouquan** [mengshukeji/Luckysheet#338]
**描述错误**
通过gulp编译出来的这几个插件在项目中都加载不了
![image](https://user-images.githubusercontent.com/29010781/101854429-7f344100-3b9c-11eb-9d02-934d056addc6.png)

**重现**
重现错误的步骤：
1.第一步操作：引入luckysheet
![image](https://user-images.githubusercontent.com/29010781/101854859-53fe2180-3b9d-11eb-92c9-bc7b4cab1a6a.png)

2.最后报错：在项目中报错，导致在Excel中有小数类型的数字会加载不出来luckysheet
![image](https://user-images.githubusercontent.com/29010781/101854893-65dfc480-3b9d-11eb-95b0-db8c7802fccc.png)

**环境：**
  -操作系统：[Windows，Mac，Linux]
  -浏览器 版本号：[Chrome 版本 84.0.4147.105（正式版本） （64 位），Safari，Firefox，Edge]
  -Luckysheet版本：[最新]

**Comment by mengshukeji** [comment]
可以提供下初始化的数据嘛

**Comment by cxmrf** [comment]
原因是numeral包并未加载至window

最简单的解决方法是：window.numeral = require('numeral')

**Comment by heyouquan** [comment]
> 可以提供下初始化的数据嘛

excel数据里面有浮点数，比如0.111，就必现这个问题

**Comment by heyouquan** [comment]
> 原因是numeral包并未加载至window
> 
> 最简单的解决方法是：window.numeral = require('numeral')

确实是没有挂载到window对象上这个问题，您那种解决方案是在业务逻辑里面写吗？那就要npm install numeral这个依赖。目前这个问题已经解决了，不过是通过在源码里面通过import numeral，再修改gulp打包的逻辑实现。

**Comment by Dushusir** [comment]
后续都会改为npm安装的方式
