### ISSUE TITLE
showtoolbarConfig 和 cellRightClickConfig 配置不起作用

### ISSUE THREAD

**Issue by zhangtaoBqteam** [mengshukeji/Luckysheet#34]
初始化添加showtoolbarConfig和cellRightClickConfig不起作用

初始化配置
![image](https://user-images.githubusercontent.com/43007011/93162989-92c03f00-f748-11ea-81a5-8750b451eb4e.png)

页面
![image](https://user-images.githubusercontent.com/43007011/93162970-850ab980-f748-11ea-8bcc-d850e72b869e.png)

**Comment by mengshukeji** [comment]
暂未实现

**Comment by YasuoHub** [comment]
这个功能还是比较实用的，建议作者大大早日提上升级日程

**Comment by Dushusir** [comment]
自定义设置已支持，欢迎体验反馈
