### ISSUE TITLE
luckysheet一开始不可编辑，点击外部按钮，可以实现单个，多个，某个区域，某行，某列，某个sheet可以编辑，不使用工具栏中的工作表保护，点击外部按钮，我选中的区域就可以编辑

### ISSUE THREAD

**Issue by 2447382228** [mengshukeji/Luckysheet#351]
**您的功能请求与问题有关吗？**
清楚简洁地说明问题。

**描述您想要的解决方案**
对您想要的功能效果简洁明了的描述。

**其他内容**
其他说明

**Comment by Dushusir** [comment]
可以。点击按钮执行[setDataVerification](https://mengshukeji.github.io/LuckysheetDocs/zh/guide/api.html#setdataverification-optionitem-setting)修改配置即可

**Comment by Dushusir** [comment]
可以。点击按钮执行[setDataVerification](https://mengshukeji.github.io/LuckysheetDocs/zh/guide/api.html#setdataverification-optionitem-setting)修改配置即可

**Comment by guodaStatham999** [comment]
用过了,  对于槽编辑是可以做限制的. 但是如果是一个范围性的粘贴是无法拦截
