### ISSUE TITLE
粘贴数据，默认使用科学计数法了

### ISSUE THREAD

**Issue by WJWM0316** [mengshukeji/Luckysheet#355]
复制一串数字 11111111111111111111111111， 选中单元格直接粘贴就默认使用科学计数法了，改变了数据格式。如果是选中单元格在编辑状态下粘贴则正常。

**Comment by luluhaya** [comment]
这个问题已经解决了吗？现在还是有这个问题

**Comment by WJWM0316** [comment]
@luluhaya  之前我是下载了源码改了一下，现在没用这个东西了，所以也不知道现在怎么样了。如果也是下载下来用的，自己改一下源码咯。 参考https://github.com/dream-num/Luckysheet/pull/415/commits/dc3cfdf44434ac191171097e0ea7f002fb7ec1fd
