### ISSUE TITLE
[BUG]updateUrl如果带了参数，会导致服务器端解析错误，原因是lucksheet会自动在updateUrl后面加上?t=111&g=XXX

### ISSUE THREAD

**Issue by qflash** [mengshukeji/Luckysheet#359]
比如设置了 updateUrl:ws://mydomain.com/ws_save?uname=abc 这样一个地址，
那么lucksheet会连接 ws://mydomain.com/ws_save?uname=abc?t=111&g=XXX
而没有判断updateUrl里面是否已经包含了?

**Comment by mengshukeji** [comment]
很好的想法，会尽快修复。如果有`?`则应该保持这样的格式

`ws://mydomain.com/ws_save?uname=abc&t=111&g=XXX`
