### ISSUE TITLE
[BUG]luckysheet初始化数据，使用transToCellData转换二维数据后，使用复制粘贴报错

### ISSUE THREAD

**Issue by scholar-xia** [mengshukeji/Luckysheet#367]
luckysheet初始化数据，使用transToCellData转换二维数据后，使用复制粘贴报错
![F6TQF4VYQP)IRI04HU2F{9L](https://user-images.githubusercontent.com/26625320/102591762-85529080-414d-11eb-9080-ec6933c5e0ad.png)
![1608190553(1)](https://user-images.githubusercontent.com/26625320/102591774-8a174480-414d-11eb-92c2-ac926eacc6de.jpg)

**Comment by mengshukeji** [comment]
我们也复现了

使用
```js
luckysheet.create({
data:[{celldata:luckysheet.transToCellData([[1,2,3,null,4],[2,3,null,5,null]])}]
})
```
初始化会出现此问题

**Comment by mengshukeji** [comment]
富文本单元格也不支持复制粘贴
![image](https://user-images.githubusercontent.com/61444807/102599820-fd728380-4158-11eb-8161-a13b8e233045.png)
