### ISSUE TITLE
[Feature request]粘贴事件api

### ISSUE THREAD

**Issue by scholar-xia** [mengshukeji/Luckysheet#368]
希望实现提供粘贴事件跟cellUpdateBefore一样功能api，可以对粘贴过来的数据在其更新之前进行处理

**Comment by mengshukeji** [comment]
可以。将会开放钩子函数：rangePasteBefore，请关注更新https://mengshukeji.github.io/LuckysheetDocs/zh/guide/config.html#rangepastebefore

**Comment by Dushusir** [comment]
已实现，请检查

**Comment by scholar-xia** [comment]
> 已实现，请检查

有个问题想问下，当我把粘贴过来的数据修改了过后，修改过的数据如何渲染出来
