### ISSUE TITLE
[BUG]发现了个bug

### ISSUE THREAD

**Issue by kkkeric** [mengshukeji/Luckysheet#369]
**描述错误**
demo页面中打印按钮没功能

**重现**
重现错误的步骤：
1，点击更多功能里面的打印
2，点击打印，弹出print 提示框
3，点击确定后，无任何反馈 

**期望的结果**
可以继续后续的打印流程

**屏幕截图或演示**

![image](https://user-images.githubusercontent.com/41583525/102598983-cbaced00-4157-11eb-82b4-b6c61fb41b39.png)

**环境：**
  -操作系统： windos 10
  -浏览器 版本号： chrome  87.0.4280.88（正式版本） （64 位）
  -Luckysheet版本：最新

**备注**
其他说明

**Comment by mengshukeji** [comment]
打印正在开发，关注此issue:
Duplicate of #188
