### ISSUE TITLE
[Feature request]隐藏、显示隐藏，在行头、列头的菜单操作，而不是在单元格的菜单。

### ISSUE THREAD

**Issue by danielcai1987** [mengshukeji/Luckysheet#37]
**您的功能请求与问题有关吗？**
Excel中，隐藏/显示隐藏 行 或者 列的操作按钮，是在 **行头** 或者 **列头** 上右键点击的菜单中显示的。例如：当右键选中列头A，整列A也被选中，菜单里有 Hide/Unhide 按钮，同时，如果在整列被选中的单元格上右键点击，菜单中会显示 Hide/Unhide按钮。
![image](https://user-images.githubusercontent.com/5369599/93281964-e04bb300-f7ff-11ea-9866-4684f6b6de19.png)

但是当单独在单元格上右键点击时，是显示另外的一个菜单，没有 Hide/Unhide 按钮，因为这两个都是对 **整行**/**整列** 的操作。
![image](https://user-images.githubusercontent.com/5369599/93282261-944d3e00-f800-11ea-9cf9-2332e9c6d671.png)

Luckysheet的相关功能，在单元格上右键点击，菜单中有 隐藏选中行、显示隐藏行，隐藏选中列、显示隐藏列 4个按钮
![image](https://user-images.githubusercontent.com/5369599/93282329-c1015580-f800-11ea-902c-448d1479a343.png)

但是在 行头、 列头 上右键点击就没有 隐藏、显示隐藏的按钮。例如：当列B被隐藏时，不能通过操作列头而**显示隐藏**。
![image](https://user-images.githubusercontent.com/5369599/93282697-8fd55500-f801-11ea-8880-ab6dec403109.png)

而是需要操作被隐藏的列B两边的A、C单元格来显示
![image](https://user-images.githubusercontent.com/5369599/93282809-cd39e280-f801-11ea-90e4-8ac228ac19d9.png)

**描述您想要的解决方案**
调整 **隐藏** 按钮出现在 **列头**、**行头**的菜单中，这样是与Excel一致的操作方式，甚至可以简化为只有 隐藏、显示隐藏2个按钮，而不需要同时显示4个按钮。如Excel， **列头**上操作就 针对**列**，**行头**上操作就针对**行**。

**Comment by wbfsa** [comment]
可以的，之后会优化
