### ISSUE TITLE
[BUG]冻结行列API

### ISSUE THREAD

**Issue by mengshukeji** [mengshukeji/Luckysheet#373]
**描述错误**
`luckysheet.setBothFrozen(true,{row_focus:0,column_focus:5})`提示没有选区

**重现**
重现错误的步骤：
1.第一步操作：打开 https://mengshukeji.github.io/LuckysheetDemo/
2.第二步操作：打开控制台：输入`luckysheet.setBothFrozen(true,{row_focus:0,column_focus:5})`
3.看到：提示没有选区

**期望的结果**
正常触发冻结

**屏幕截图或演示**
![image](https://user-images.githubusercontent.com/61444807/102733536-83b8e080-4378-11eb-8374-248aaeda611d.png)

**环境：**
  -操作系统：[Windows]
  -浏览器 版本号：[Edge Version 87.0.664.66 (Official build) (64-bit)]
  -Luckysheet版本：[最新]

**Comment by wpxp123456** [comment]
不应该是luckysheet.setBothFrozen(true, { range: {row_focus:0,column_focus:5} }) 吗
