### ISSUE TITLE
[BUG]单元格输入值为小数时，无法结束单元格编辑

### ISSUE THREAD

**Issue by china-jingxu** [mengshukeji/Luckysheet#379]
控制台错误信息如下：
[
![5$3(CC`@(U6`ZUDY)9FSB{1](https://user-images.githubusercontent.com/22165374/102762312-11b1bd00-43b3-11eb-9d07-78d608094c19.png)
](url)
**环境：**
  -操作系统：[例如 Windows]
  -浏览器 版本号：[例如 Firefox版本84.0（正式版本） （64 位）]
  -Luckysheet版本：[最新]

**Comment by flowerField** [comment]
能否提供重现该错误信息的具体操作细节，谢谢！
