### ISSUE TITLE
[BUG]functionButton not working

### ISSUE THREAD

**Issue by mengshukeji** [mengshukeji/Luckysheet#381]

**Comment by fmr2023** [comment]
![K}$B)H8U_0Q_%%799{`26{P](https://user-images.githubusercontent.com/70942974/102856473-85120800-4461-11eb-9fa3-19bea0533752.png)
![U9RQLNF)V~24QSQRT}%XBP8](https://user-images.githubusercontent.com/70942974/102856481-86dbcb80-4461-11eb-8292-58b2380e1667.png)

这个功能失效！

**Comment by fmr2023** [comment]
functionButton:'<button id="" class="btn btn-primary" style="padding:3px 6px;font-size: 12px;margin-right: 10px;">下载</button> <button id="" class="btn btn-primary btn-danger" style=" padding:3px 6px; font-size: 12px; margin-right: 10px;">分享</button> <button id="luckysheet-share-btn-title" class="btn btn-primary btn-danger" style=" padding:3px 6px; font-size: 12px; margin-right: 10px;">秀数据</button>',
         

这个，option中所有的度可以   唯独这个没有效果

**Comment by JasonChiang1916** [comment]
me too
