### ISSUE TITLE
在tab选项卡中切换出现的bug

### ISSUE THREAD

**Issue by scholar-xia** [mengshukeji/Luckysheet#393]
bug1：当把luckysheet放入选项卡中，激活单元格后切换选项卡，激活的单元格还在。
bug2：当把luckysheet放入选项卡中，把表格向下滚动后切换选项卡，再切换回来，滚动条位置显示错误但表格内容显示正确，这时向下滚动表格内容会从头开始计算显示
![6F{O@L VI7SE}`39NIFTT{0](https://user-images.githubusercontent.com/26625320/103063760-401adc80-45ed-11eb-928e-05e4f4978260.png)
![@$6W2@YNP BSHZY90 9(_21](https://user-images.githubusercontent.com/26625320/103063763-43ae6380-45ed-11eb-8aab-d7c5f7d2e2a9.png)

**Comment by scholar-xia** [comment]
![1](https://user-images.githubusercontent.com/26625320/103063953-b15a8f80-45ed-11eb-9829-6a167317f438.png)
![2](https://user-images.githubusercontent.com/26625320/103063959-b4558000-45ed-11eb-98b4-31f9fc40b7e5.png)
![3](https://user-images.githubusercontent.com/26625320/103063962-b6b7da00-45ed-11eb-96f7-ccab7615cc2f.png)

**Comment by Dushusir** [comment]
bug1：可以在切换tab之前执行下`luckysheet.exitEditMode()`
bug2:  现在页面多实例存在DOM共享问题，现在推荐每次打开重新创建表格，或者采用iframe隔离。

多实例正在优化，请关注：Duplicate of #97

**Comment by jsjgsr** [comment]
> bug1：可以在切换tab之前执行下`luckysheet.exitEditMode()` bug2: 现在页面多实例存在DOM共享问题，现在推荐每次打开重新创建表格，或者采用iframe隔离。
> 
> 多实例正在优化，请关注：Duplicate of #97

我在新页面重新创建表格的时候，出现了含有公式的单元格被上一个页面表格实例有公式的单元格污染的情况。正确的销毁和创建实例的方法应该是怎样的。我用的是create与destroy
