### ISSUE TITLE
[Feature request]拷贝单元格数据，是否支持 携带公式

### ISSUE THREAD

**Issue by OPerri** [mengshukeji/Luckysheet#40]
1.目前excel拷贝单元格数据(包含公式)至luckysheet，只有数值被粘贴过来，但是公式没有携带过来
2.sheet页之间拷贝单元格数据 (包含公式) 也是如此

**Comment by wbfsa** [comment]
第一个问题没有办法解决，因为浏览器是不允许访问剪切板的，我们只是用了hacker方法，所以从excel复制过来的数据本身就不带公式。可以试试luckyexcel直接导入excel。
第二个问题，有个矛盾点，因为剪切板的限制我们无法判断是否从excel拷贝了数据，所以复制了luckysheet数据之后，再切换页进行粘贴，我们不知道是该用从excel复制的外部数据还是lucky本身的数据。所以现在默认只要切换页，都是读取从excel拷贝的内容。

**Comment by Dushusir** [comment]
> 1.目前excel拷贝单元格数据(包含公式)至luckysheet，只有数值被粘贴过来，但是公式没有携带过来
> 2.sheet页之间拷贝单元格数据 (包含公式) 也是如此
sheet页之间拷贝单元格数据 (包含公式)现在已生效

**Comment by OPerri** [comment]
非常感谢！
