### ISSUE TITLE
[BUG]The freeze function is different from excel 冻结和excel表现不一致

### ISSUE THREAD

**Issue by Dushusir** [mengshukeji/Luckysheet#409]
**Description**
The freeze of the merged cell, the default is the lower right corner of the first cell, but excel is to get the upper left corner of the entire merged cell

**描述错误**
合并单元格的冻结，默认取的是第一个单元格的右下角位置，但是excel是取得整个合并单元的左上角

**屏幕截图或演示**
Luckysheet:
![image](https://user-images.githubusercontent.com/26371161/103263392-bac76b80-49e2-11eb-8697-b406107b6fbb.png)

excel:
![image](https://user-images.githubusercontent.com/26371161/103263477-f9f5bc80-49e2-11eb-9bcf-c9ba858abe97.png)

**Comment by Gentear** [comment]
这个问题后来解决了么
