### ISSUE TITLE
[BUG]'fullscreenmode: false' does not work

### ISSUE THREAD

**Issue by kmptkp** [mengshukeji/Luckysheet#41]
**Description**
Option 'fullscreenmode: false' does not work. I first tried by simply passing it as an option (see below) and verifying in the debugger that the option is passed correctly (it is passed correctly). This had no effect, I still saw a fullscreen spreadsheet. Then I downloaded the cdn js file luckysheet.umd.js, and edited it to change the default to be 'false' (!1) rather than true (!0). Reloading with an html file pointing at this changed version still gave me a fullscreen spreadsheet.

**To Reproduce**
Follow the exact instructions you give to use luckysheet. In the options object, just add one line: 'fullscreenmode: false,'.

**What is expected?**
The other divs on the page should show side by side with the luckysheet spreadsheet. They don't.

**Environment**
 - OS: Linux
 - Browser Version: Firefox Nightly 82, Chromium 85
 - Luckysheet Version: latest

**Comment by wbfsa** [comment]
The fullscreenmode is legacy config, You can try change config to hide menu. for example:
```
luckysheet.create({
  showtoolbar:false,
  showinfobar:false,
  showsheetbar:false,
  showstatisticBar:false
});
```
