### ISSUE TITLE
[Bug] 关于toolbar显隐效果的问题

### ISSUE THREAD

**Issue by morningsun42** [mengshukeji/Luckysheet#414]
luckysheet的toolbar工具条是通过toobarWidths里每个控件的left来计算显隐的，
如果luckysheet不是在窗体最左侧，这时候toobarWidths的left会取错，这个left应该减去luckysheet的left才合适，
![image](https://user-images.githubusercontent.com/40629010/103340796-fedc6e00-4abf-11eb-80b1-d914bd232b6a.png)

通过修改Store.container为document.body来影响gridW = $("#" + Store.container).width();可以解决此问题，但是因为container改变了，luckysheet的遮罩层也会占据全页面会很难看，应该也不是开发者的初衷。
目前解决办法如下，期待官网有更好的解决办法

![image](https://user-images.githubusercontent.com/40629010/103340907-495dea80-4ac0-11eb-811c-f191de77996a.png)

**Comment by mengshukeji** [comment]
谢谢提供建议和想法

**Comment by Dushusir** [comment]
> luckysheet的toolbar工具条是通过toobarWidths里每个控件的left来计算显隐的，
> 如果luckysheet不是在窗体最左侧，这时候toobarWidths的left会取错，这个left应该减去luckysheet的left才合适，
> ![image](https://user-images.githubusercontent.com/40629010/103340796-fedc6e00-4abf-11eb-80b1-d914bd232b6a.png)
> 
> 通过修改Store.container为document.body来影响gridW = $("#" + Store.container).width();可以解决此问题，但是因为container改变了，luckysheet的遮罩层也会占据全页面会很难看，应该也不是开发者的初衷。
> 目前解决办法如下，期待官网有更好的解决办法
> 
> ![image](https://user-images.githubusercontent.com/40629010/103340907-495dea80-4ac0-11eb-811c-f191de77996a.png)

Optimized the toolbar position of the toolbar and more buttons when Luckysheet does not occupy the full screen

![image](https://user-images.githubusercontent.com/26371161/110592945-e4a4c780-81b5-11eb-95ff-33cd4682835b.png)

![image](https://user-images.githubusercontent.com/26371161/110593003-f4bca700-81b5-11eb-964e-7fdf696fd078.png)
