### ISSUE TITLE
[BUG]发现了个bug

### ISSUE THREAD

**Issue by tqqecell** [mengshukeji/Luckysheet#43]
创建 excel 表格的参数data 为每个sheet 配置 row、column 的数量无效。查看代码 _this.nulldata 创建时只考虑了defaultrowNum、defaultcolumnNum参数配置。file.data 考虑了 sheet 配置 row、column。不解为啥要这样做？
在 createdom.js 中发现了最少30行22列的限定。

**Comment by wbfsa** [comment]
之后修复这个内容

**Comment by Dushusir** [comment]
Duplicate of #42
