### ISSUE TITLE
[Feature request] The loadUrl interface adds paging fetch data capability 建议 loadUrl接口增加分页获取数据功能

### ISSUE THREAD

**Issue by yuelaotou** [mengshukeji/Luckysheet#440]
我建议 loadUrl接口增加分页获取数据功能。当总数据量过10M，那速度可是很慢很慢的。

所以，建议是：
1、loadUrl增加分页获取数据功能，当然可以仅限image和celldata。
2、分页时机是向下滚动时，所谓的异步加载的效果。
3、后台根据分页的page和size属性去按照前端要求输出结果。

I recommend that the loadUrl interface add paging fetch data capability. When the total data exceeds 10M, the speed is very, very slow.

So, the advice is:
1. LoadUrl adds paging fetch function, which can only be used for image and cellData.
2. The timing of paging is the effect of the so-called asynchronous loading when scrolling down.
3. The background outputs the results according to the front end requirements according to the page and size properties of pagination.

**Comment by mengshukeji** [comment]
现在已有分页器设置：

### pager
- 类型：Object
- 默认值：null
- 作用：分页器按钮设置，初版方案是直接使用的jquery插件 [sPage](https://github.com/jvbei/sPage)
	点击分页按钮会触发钩子函数 `onTogglePager`，返回当前页码，同`sPage`的`backFun`方法，此分页器设置只负责UI部分，具体切换分页后的数据请求和数据渲染，请在`onTogglePager`钩子行数里自定义处理。
	```js
	pager: {
		pageIndex: 1, //当前的页码
		pageSize: 10, //每页显示多少行数据
		total: 50, //数据总行数
		selectOption: [10, 20] //允许设置每页行数的选项
	}
	```

比较初级，但是可以依照这个来定制自己的数据加载

**Comment by mengshukeji** [comment]
文档不久会更新

**Comment by yerzhant** [comment]
Hi @mengshukeji 
What is the right way of doing a paging?
