### ISSUE TITLE
[Feature request] Need for protected sheets / locked cells

### ISSUE THREAD

**Issue by mnohn** [mengshukeji/Luckysheet#45]
**PROTECT SHEETS AND CONTENT IN LOCKED CELLS**

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
It is not possible to protect the spreadsheet and to lock cells so that users of a preconfigured spreadsheet cannot mess up the formulas.

**Describe the solution you'd like**
to be able to protect sheets and the content of locked cells on these sheets (as in Excel)

**Additional context**
excel equivalent...
<img width="619" alt="Screen Shot 2020-09-17 at 16 25" src="https://user-images.githubusercontent.com/69317456/93484750-95669400-f902-11ea-96e3-d4148732ade3.png">
<img width="446" alt="Screen Shot 2020-09-17 at 16 25 1" src="https://user-images.githubusercontent.com/69317456/93484762-97305780-f902-11ea-99d9-6140bbd8ab26.png">

**Comment by wbfsa** [comment]
Ok, this is added task list.

**Comment by siflu** [comment]
This feature would be highly appreciated :)

**Comment by marek-baranowski** [comment]
I would appreciate this feature very much!

**Comment by wbfsa** [comment]
Protection is already supported in the latest version, update the api later. @mnohn @siflu @marek-baranowski 
It can also be set via menu button on the far right, locked and hidden cell is set by right click menu.
`
                                    "config": {
						"authority":{
							selectLockedCells:1,
							selectunLockedCells:1,
							formatCells:1,
							formatColumns:1,
							formatRows:1,
							insertColumns:1,
							insertRows:1,
							insertHyperlinks:1,
							deleteColumns:1,
							deleteRows:1,
							sort:1,
							filter:1,
							usePivotTablereports:1,
							editObjects:1,
							editScenarios:1,
							
							sheet:1,//If 1 or true then the sheet is protected.If 0 or false then the sheet is not protected.
							password:"",
							hintText:"",
							algorithmName:"None",//None,MD2,MD4,MD5,RIPEMD-128,RIPEMD-160,SHA-1,SHA-256,SHA-384,SHA-512,WHIRLPOOL
							saltValue:null,
							checkSheetPasswordUrl:null,

							//range authority
							allowRangeList:[{
								name:"区域",
								password:"1",
								hintText:"",
								algorithmName:"None",//None,MD2,MD4,MD5,RIPEMD-128,RIPEMD-160,SHA-1,SHA-256,SHA-384,SHA-512,WHIRLPOOL
								saltValue:null,
								checkRangePasswordUrl:null,
								sqref:"$C$1:$D$5"
							}],
						}
                                          }
`

**Comment by mnohn** [comment]
Thank you, @wbfsa !!
