### ISSUE TITLE
[BUG]单元格取消合并后会导致数据联动。

### ISSUE THREAD

**Issue by sjk971106** [mengshukeji/Luckysheet#450]
**描述错误**
清楚简洁地描述错误是什么。
已合并的单元格再取消合并后会发生数据联动。
**重现**
重现错误的步骤：
1.第一步操作
选择多个单元格进行合并
2.第二步操作
取消合并的单元格
3.第三步操作
修改单元格内容或样式
4.最后看到了什么错误
其他单元格样式及内容同时跟着当前修改的单元格进行变化
**期望的结果**
对您期望发生的结果简洁明了的描述。
取消单元格之间的联动
**屏幕截图或演示**
方便的话，贴上屏幕截图或在线链接复现问题，我们复测时会更精准

**环境：**
  -操作系统：[例如 Windows，Mac，Linux]
  -浏览器 版本号：[例如 Chrome 版本 84.0.4147.105（正式版本） （64 位），Safari，Firefox，Edge]
  -Luckysheet版本：[例如 1.0.1，最新]
Windows,google
**备注**
其他说明
一、
查看源代码发现问题在 src/global/setdata.js  15行

13.   // 若采用深拷贝，初始化时的单元格属性丢失
14.   // let cell = $.extend(true, {}, d[r][c]);
15.    let cell = d[r][c];

通过对15行修改发现解决了这个问题，但是不知道会带来什么影响。希望可以尽快修改此bug。
修改方案
let cell = JSON.parse(JSON.stringify(d[r][c]));
二、
造成此bug的另一个原因应该就是在取消合并时在创建单元格的方式上没有考虑引用类型变量的特性，导致数据指针都指向同一堆内存中的对象。

**Comment by flowerField** [comment]
感谢！
这个问题在 解决合并单元格后取消合并操作创建cell的地址引用问题 #434 被修复，http://luckysheet.lashuju.com/demo/的代码并非最新版本，可以下载最新代码重新验证。
