### ISSUE TITLE
[BUG]updateImageUrl 不知如何使用。

### ISSUE THREAD

**Issue by yuelaotou** [mengshukeji/Luckysheet#452]
updateImageUrl 不知如何使用。

1、updateImageUrl 应该不是表格操作那些东东吧，比如https://mengshukeji.github.io/LuckysheetDocs/zh/guide/operate.html#%E5%8D%95%E5%85%83%E6%A0%BC%E5%88%B7%E6%96%B0这里的东东。
2、我看是单独的后端接口。我看了server.js 代码，是个post请求，2个入参，gridKey和data，但把表格中的某图片缩小后，socket就断开了。请求不到后端。然后，server.js里也不知道走到哪了。。。 没跟进去代码。

能不能出个image如何操作的开发教程。比如：
1、首页load的时候，image是可以异步的吗？ 我没看出来是这样。但蛮希望的。
2、图片更新的时候，这个接口data里面到底是啥，我现在还走不到。我希望能对data进行描述，后端需要干啥。
3、到底是走工作表操作的各个东东，还是单独的这个接口，我还没弄清楚。

**Comment by mengshukeji** [comment]
updateImageUrl是表格缩略图用的，不是插入的图片的保存。

插入的图片的保存走的是通用保存，类似于
```js
  {
      "t": "all",
      "k": "images"
  }
```
![image](https://user-images.githubusercontent.com/61444807/104868902-9591a180-597f-11eb-8d5e-9717455224bc.png)
