### ISSUE TITLE
[Feature request] "End-user view"

### ISSUE THREAD

**Issue by mnohn** [mengshukeji/Luckysheet#46]
**Is your feature request related to a problem? Please describe.**
Context: We would like to embed the luckytable in a simple web interface for end users. Currently end users get confused with menu, toolbar, column and row headers, etc. 

**Describe the solution you'd like**
Thus end users shall NOT have the option (nor need the option) to code/edit/layout the model, with exception of few cells that are preconfigured for user inputs. 

Moreover, we would love a simple and clean representation/view of the coded spreadsheet for end users - without any of the menus, tools (e.g. formatting table) and the column and row headers. 

Related is request #45 about protecting the spreadsheet: in the end user representation, one would only be able to make few inputs in predefined cells and then the model will provide the output.  

**Additional context**
Hope it's clear, am available for questions, and would be very happy to get this feature. thank you!

**Comment by wbfsa** [comment]
hello,  
1. You can try change config to hide menu. for example:
```
luckysheet.create({
  showtoolbar:false,
  showinfobar:false,
  showsheetbar:false,
  showstatisticBar:false
});
```
we are developing about feature of hidden row and column title.

2. Custom menus are opening related interfaces
3. The feature of  lock cell is added task list.

**Comment by mnohn** [comment]
Thank you for #1!

**Comment by mengshukeji** [comment]
The feature of lock cell is done, please check this worksheet configuration [config.authority](https://mengshukeji.github.io/LuckysheetDocs/guide/sheet.html#config-authority)

**Comment by mnohn** [comment]
Perfect. We will implement it and revert with questions or suggestions or bug info. In any case, thank you a lot!
