### ISSUE TITLE
只读模式

### ISSUE THREAD

**Issue by codingbycat** [mengshukeji/Luckysheet#461]
希望能够添加只读模式，禁用编辑状态，有些特定场景下我需要Luckysheet禁用编辑只能浏览

**Comment by flowerField** [comment]
可以在初始化 luckysheet调用 luckysheet.create(options)的配置项options中设置 allowEdit 的值为false，来配置表格只允许前台编辑模式，该配置项默认值为 true，可以在下列文件代码中找到该配置：

```javascript
    //文件：src/config.js
    /**
     * The default luckysheet config object.
     */
    export default {
        container: "luckysheet", //容器的ID
        column: 60, //空表格默认的列数量
        row: 84, //空表格默认的行数据量
        allowCopy: true, //是否允许拷贝
       ....
        myFolderUrl: "www.baidu.com", //左上角<返回按钮的链接
        config: {}, //表格行高、列宽、合并单元格、公式等设置
        fullscreenmode: true, //是否全屏模式，非全屏模式下，标记框不会强制选中。
        devicePixelRatio: window.devicePixelRatio, //设备比例，比例越大表格分标率越高
        allowEdit: true, //是否允许前台编辑
        loadUrl: "", // 配置loadUrl的地址，luckysheet会通过ajax请求表格数据，默认载入status为1的sheet数据中的所有data，其余的
       ....
```

如果需要对UI或交互进行调整，在代码中，可以通过 Store.allowEdit === false 的方式来进行判断区分。

不知上面的描述 能否解决您的问题？

**Comment by codingbycat** [comment]
> 可以在初始化 luckysheet调用 luckysheet.create(options)的配置项options中设置 allowEdit 的值为false，来配置表格只允许前台编辑模式，该配置项默认值为 true，可以在下列文件代码中找到该配置：
> 
> ```js
>     //文件：src/config.js
>     /**
>      * The default luckysheet config object.
>      */
>     export default {
>         container: "luckysheet", //容器的ID
>         column: 60, //空表格默认的列数量
>         row: 84, //空表格默认的行数据量
>         allowCopy: true, //是否允许拷贝
>        ....
>         myFolderUrl: "www.baidu.com", //左上角<返回按钮的链接
>         config: {}, //表格行高、列宽、合并单元格、公式等设置
>         fullscreenmode: true, //是否全屏模式，非全屏模式下，标记框不会强制选中。
>         devicePixelRatio: window.devicePixelRatio, //设备比例，比例越大表格分标率越高
>         allowEdit: true, //是否允许前台编辑
>         loadUrl: "", // 配置loadUrl的地址，luckysheet会通过ajax请求表格数据，默认载入status为1的sheet数据中的所有data，其余的
>        ....
> ```
> 
> 如果需要对UI或交互进行调整，在代码中，可以通过 Store.allowEdit === false 的方式来进行判断区分。
> 
> 不知上面的描述 能否解决您的问题？

抱歉，没有察觉到该配置项！我已关闭该issue

**Comment by libbGit** [comment]
我发现了两种方式，在config中可以配置，一个是 allowEdit:false, 它连给文字添加背景，颜色，下划线都不行。完全不能编辑。
而editMode: true（没错就是true），就是仅仅能编辑样式，必须背景颜色，合并单元格等等。但不能编辑单元格值

**Comment by gongxiansheng** [comment]
禁止编辑 需要两个参数  editMode:false,allowEdit: false

**Comment by khiha** [comment]
只读模式下，可以配置某一列或者某一行只读吗？其他列或行可以编辑，比如在单元格中配置
