### ISSUE TITLE
[BUG]rowhidden设置无效，表格加载时仍然会显示应该隐藏的行

### ISSUE THREAD

**Issue by danielcai1987** [mengshukeji/Luckysheet#47]
**描述错误**
表格加载时，会把config.rowhidden清空，设置为{}。导致本应隐藏的**行**显示出来了

**重现**
重现错误的步骤：

1. 可参见Demo，https://mengshukeji.github.io/LuckysheetDemo/
2. 第31、32行，数据里设置的是

`"rowhidden": {
			"30": 0,
			"31": 0
		}`
但加载到Luckysheet之后，在console.log("DATA",luckysheet.getluckysheetfile()[0]);可以看到 rowhidden:{}

**期望的结果**
colhidden是正常的，希望把rowhidden的bug修复

**屏幕截图或演示**
![image](https://user-images.githubusercontent.com/5369599/93590027-6292cd80-f9e0-11ea-902f-9aed4eddfc87.png)

**环境：**
  -操作系统：[Windows 10]
  -浏览器 版本号：[例如 Chrome 版本 85.0.4183.83 （正式版本） （64 位）]
  -Luckysheet版本：[最新]

**Comment by Dushusir** [comment]
check the demo sheet:"Cell"(lastest code)
