### ISSUE TITLE
[BUG]defaultFontSize无效

### ISSUE THREAD

**Issue by mengshukeji** [mengshukeji/Luckysheet#475]
**描述错误**
luckysheet.create({defaultFontSize:20})

**重现**
重现错误的步骤：
1.第一步操作：打开demo: https://mengshukeji.github.io/LuckysheetDemo/
2.第二步操作：控制台输入：luckysheet.create({defaultFontSize:20})
3.最后看到了什么错误：编辑任一单元格，默认字体没有改变

**期望的结果**
编辑任一单元格，默认字体大小是 20px

**屏幕截图或演示**
![image](https://user-images.githubusercontent.com/61444807/104985305-9a238c00-5a4b-11eb-9fb8-6981def80d5e.png)

**环境：**
  -操作系统：[Windows]
  -浏览器 版本号：[Edge]
  -Luckysheet版本：[最新]

**备注**
其他说明

**Comment by nic2sim** [comment]
This is still not working for me in version 2.1.13.
