### ISSUE TITLE
[Feature request]单页面应用，无法手动关闭websocket连接，会导致建立多个连接

### ISSUE THREAD

**Issue by fandypeng** [mengshukeji/Luckysheet#478]
使用vue搭建的单页面应用，多次初始化luckysheet实例，会跟服务器建立多个websocket连接，实例无法主动关闭连接，这会导致连接断开的时候出现多个错误弹框，希望增加一个API可以手动关闭实例连接，或者在destory函数里面增加关闭链接的操作。

**Comment by mengshukeji** [comment]
`luckysheet.closeWebsocket()`

**Comment by fandypeng** [comment]
> `luckysheet.closeWebsocket()`

调用这个函数手动关闭连接，没有清理掉定时器retryTimer，这会导致控制台持续报错
`server.js:172 WebSocket is already in CLOSING or CLOSED state.
(anonymous) @ server.js:172
setInterval (async)
e.websocket.onopen @ server.js:171`
