### ISSUE TITLE
[BUG]JS浮点数运算结果不精确，导致公式计算结果错误

### ISSUE THREAD

**Issue by danielcai1987** [mengshukeji/Luckysheet#49]
**描述错误**
JS浮点数运算结果不精确，导致公式计算结果错误

**重现**
重现错误的步骤：
1. 在 https://mengshukeji.github.io/LuckysheetDemo/ 输入数据
```
A1: 0.3
B1: 0.3
C1: 0.3
D1: 0.1
A2: =1-SUM(A1:D1)
```
2. 期待结果 A2 = 0
3. 实际计算结果 A2 = 1.11022e-16

**期望的结果**
解决JS浮点数运算结果不精确的Bug
参考1：https://juejin.im/post/6844903903071322119
参考2： https://github.com/camsong/blog/issues/9

**屏幕截图或演示**
![image](https://user-images.githubusercontent.com/5369599/94008689-ffd17580-fdd5-11ea-98a6-5434249f3893.png)

**环境：**
  -操作系统：[Windows]
  -浏览器 版本号：[例如 Chrome Version 85.0.4183.83 (Official Build) (64-bit)]
  -Luckysheet版本：[最新]

**Comment by wbfsa** [comment]
使用numral解决了
