### ISSUE TITLE
[BUG]sheetActivate钩子不生效

### ISSUE THREAD

**Issue by Wizard-yin** [mengshukeji/Luckysheet#494]
**Describe the bug**

**To Reproduce**
1. The first step
2. The second step
3. The third step

**What is expected?**

**Screenshots or demo**
If applicable, add screenshots or online demo to help explain your problem.We will be more accurate when we retest.

**Environment**
 - OS: [e.g. Windows,Mac,Linux]
 - Browser Version: [e.g. Chrome Version 84.0.4147.105 (Official Build) (64-bit), Safari,Firefox,Edge]
 - Luckysheet Version: [e.g. 1.0.1,latest]

**Additional context**

**Comment by mengshukeji** [comment]
新版可以触发，请更新到最新版
