### ISSUE TITLE
使用luckysheet.setcellvalue方法设置表格边框 设置完成之后不生效

### ISSUE THREAD

**Issue by gaoshiyong1272** [mengshukeji/Luckysheet#5]
使用luckysheet.setcellvalue方法设置表格边框 设置完成之后不生效，代码如下

var obj = {
					v: tab_value,
					fc: '#f90',
					bc: '#000',
					bs: 'Thick',
					ht: '0',
					vt: '0',
					tb: 1,
					//bg: '#f60',
					bs_t: 'Thick',
					bc_t: '#000',
				};
				
				luckysheet.setcellvalue(target.row, target.column, luckysheet.flowdata, obj);
				luckysheet.luckysheetrefreshgrid();

**Comment by mengshukeji** [comment]
Duplicate of #6
