### ISSUE TITLE
[BUG] Find&Replace also replaces in locked cells

### ISSUE THREAD

**Issue by mikeungers** [mengshukeji/Luckysheet#519]
**Describe the bug**
When using Find&replace with activated sheet protection also content of locked cells is modified.

**To Reproduce**
1. Enter some text in a random cell (cell should be locked by default)
2. Protect the sheet
3. Use find&replace to replace the text
4. Content of the cell is replaced

**What is expected?**
Find&Replace should only affect cells which are editable by the user when protection is activated.

**Environment**
 - OS: Windows 10
 - Browser Version: Chrome Version 87.0.4280.141
 - Luckysheet Version: 2.1.13

**Comment by mengshukeji** [comment]
Fixed
