### ISSUE TITLE
扩展功能：支持以只读方式打开Luckysheet

### ISSUE THREAD

**Issue by EricYang1970** [mengshukeji/Luckysheet#524]
有时需要以只读方式打开 luckysheet，只支持复制等操作。

**Comment by sunjingwu** [comment]
该功能实现了？还是不准备实现了？

**Comment by EricYang1970** [comment]
已实现




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mengshukeji/Luckysheet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月9日(星期五) 下午3:11
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [mengshukeji/Luckysheet] 扩展功能：支持以只读方式打开Luckysheet (#524)





 
该功能实现了？还是不准备实现了？

**Comment by sunjingwu** [comment]
谢谢，已经看到。

**Comment by sunjingwu** [comment]
但是发现一个新的问题：从excel中过来的字符串中包含“\n”,渲染出来没有换行效果，但双击进入编辑模式然后再退出，就会重现换行的效果。不知有没有好的处理方式？

**Comment by cdbEvan** [comment]
请问如何实现只读？是用哪一个配置参数
