### ISSUE TITLE
[BUG]数据条类型条件格式问题

### ISSUE THREAD

**Issue by Amatsukaze22** [mengshukeji/Luckysheet#528]
问题：
问题复现步骤
1.在单元格中填入一个字符串

2.选中单元格，将单元格格式设置为数字

3.将当前单元格的条件格式设置为数据条，此时前端会报错，如下图所示
![image](https://user-images.githubusercontent.com/23382377/108481916-be38ee00-72d3-11eb-8810-4f6f8b7ac97e.png)

能否在单元格值为字符串的情况下，不对数据条进行渲染，但保留条件格式的设定？

重现环境
操作系统: Windows 10
浏览器版本: Chrome Version 87.0.4280.141
LuckySheet版本：2.1.13

**Comment by Size-of** [comment]
@I can solve it

**Comment by Size-of** [comment]
@I can solve it
