### ISSUE TITLE
[BUG]ALT+enter换行后单无格文字字体类型及字体大小丢失

### ISSUE THREAD

**Issue by SuyongSun** [mengshukeji/Luckysheet#53]
**描述错误**
使用alt+enter换行后，单无格文字字体及大小丢失

**重现**
重现错误的步骤：
1.第一步正常情况
![image](https://user-images.githubusercontent.com/12286518/94353603-8f607800-00a5-11eb-9ace-aba51ef1df81.png)
2.换行后字体丢失，当字体为bold时，字号也会丢失，会从原来的字号变为12号
![image](https://user-images.githubusercontent.com/12286518/94353619-be76e980-00a5-11eb-8e06-b17809a9496a.png)
![image](https://user-images.githubusercontent.com/12286518/94353621-c171da00-00a5-11eb-898e-ca642eb2881c.png)

**Comment by wbfsa** [comment]
Already fixed
