### ISSUE TITLE
[BUG]日期类型格式化显示有误

### ISSUE THREAD

**Issue by cdswyda** [mengshukeji/Luckysheet#540]
**描述错误**

master 分支下构建出的代码，日期类型格式化显示有误

**重现**
重现错误的步骤：
1. 设置单元格格式为 日期
2. 点击单元格进入控件 选择日期
3. 可以看到显示结果不对

**期望的结果**

应显示选择的日期

**屏幕截图或演示**
方便的话，贴上屏幕截图或在线链接复现问题，我们复测时会更精准

![2021-03-02](https://user-images.githubusercontent.com/13060680/109628261-80fb1880-7b7d-11eb-8179-93701d5e30de.gif)

**环境：**
  -操作系统：Windows
  -浏览器 版本号：Google Chrome 版本 88.0.4324.190（正式版本）
  -Luckysheet版本：master 分支构建版本

**备注**
无

**Comment by mengshukeji** [comment]
@flowerField 这个问题看看？ 应该是format.js 1355行修改后引起的
