### ISSUE TITLE
[Feature request] Custom Button

### ISSUE THREAD

**Issue by EAzari** [mengshukeji/Luckysheet#59]
Could you please add a custom button feature that is able to customize buttons (and even other fields, like checkboxes, radios, ...)?

How can I build clickable buttons inside the cells that change their output results when clicked multiple times:

For instance, I want to build this table that has custom buttons: 
![0](https://user-images.githubusercontent.com/39350101/94995357-9fe38780-05aa-11eb-8035-0303cc2ec85e.png)

Some other questions: Luckysheet can show just used cells? And does support multiple headers?

**Comment by wbfsa** [comment]
1. Button is unsupported, checkboxes and dropdownlist is supported, you can try the data verification feature.
2. Cells will support click event.
3. What exactly does multiple headers refer to?  The style in the picture is currently supported.

**Comment by EAzari** [comment]
Thank you @wbfsa, I close this issue
