### ISSUE TITLE
luckysheet.setcellvalue 设置单元格的值

### ISSUE THREAD

**Issue by gaoshiyong1272** [mengshukeji/Luckysheet#6]
luckysheet.setcellvalue(1,1,luckysheet.flowdata,{v:1})
luckysheet.luckysheetrefreshgrid();

设置完成之后，使用headerbar上面的功能（比如使用居中对齐，合并单元格），数据消失

**Comment by liuyang3688** [comment]
我这里是没有复现你说的

**Comment by mengshukeji** [comment]
> luckysheet.setcellvalue(1,1,luckysheet.flowdata,{v:1})
> luckysheet.luckysheetrefreshgrid();
> 
> 设置完成之后，使用headerbar上面的功能（比如使用居中对齐，合并单元格），数据消失

试试
```js
luckysheet.setcellvalue(1,1,luckysheet.flowdata,{v:1})
luckysheet.jfrefreshgrid(luckysheet.flowdata,[]);
```
