### ISSUE TITLE
[BUG]No luckysheet.umd.js in dist

### ISSUE THREAD

**Issue by d01010101** [mengshukeji/Luckysheet#63]
I have built the sources of the current snapshot with `npm run build`, but there is no `luckysheet.umd.js` required by the following line from README: `<script src="https://cdn.jsdelivr.net/npm/luckysheet/dist/luckysheet.umd.js"></script>`.

All scripts:
````
$ find . -name "*.js"
./assets/iconfont/iconfont.js
./plugins/js/plugin.js
./expendPlugins/chart/chartmix.umd.min.js
./demoData/sheetChart.js
./demoData/sheetCell.js
./demoData/sheetTable.js
./demoData/sheetSparkline.js
./demoData/sheetDataVerification.js
./demoData/sheetConditionFormat.js
./demoData/sheetPivotTable.js
./demoData/sheetComment.js
./demoData/sheetFormula.js
./demoData/sheetPivotTableData.js
./demoData/sheetPicture.js
````

**Comment by wbfsa** [comment]
Make sure?
![20201008212019](https://user-images.githubusercontent.com/68851825/95464111-284b9900-09ac-11eb-9d0f-c217b0d2376c.png)

**Comment by d01010101** [comment]
Possibly I made a mistake before, because now I recompiled and the files are there.
