### ISSUE TITLE
[BUG]Something is wrong with scaling

### ISSUE THREAD

**Issue by d01010101** [mengshukeji/Luckysheet#64]
I use the snapshot sources. I followed "Get started". So I have put the widget into `<div id="luckysheet" style="margin:0px;padding:0px;position:absolute;width:100%;height:100%;left: 0px;top: 0px;"></div>`. However, it turned out that the div inside, of the class `luckysheet`, had dimensions of 100x100 pixels. I needed to resize the browser just to make the div scale. It scaled too large, though. I attach a screenshot with "double" scrollbars. I would expect the external scrollbars to not exist at all. Probably, the widget thinks that is is smaller, when in reality it is larger. One of the reasons might be `local cache restored` information, which goes beyond the right margin, and also the large  branding at the top.

- is there some resize api, to inform the widget that it should initially resize itself?
- how to get rid of the info about cache which looks like debugging, and which may cause the scaling problems?
- how to remove the branding, which may also cause the scaling problems? I would want a clean widget in a `div`.

![luckysheet](https://user-images.githubusercontent.com/26835047/95462005-37fcba80-0977-11eb-9e2e-aa190ea352c4.png)

**Comment by wbfsa** [comment]
You can look at this api:
https://mengshukeji.github.io/LuckysheetDocs/guide/api.html#resize-setting

**Comment by d01010101** [comment]
`luckysheet.resize();` causes a JS error: `Uncaught TypeError: luckysheet.resize is not a function`.

**Comment by wbfsa** [comment]
Is the latest version? I tried it

**Comment by d01010101** [comment]
No, it is not the latest snapshot! I am sorry. Because of some problems, I changed for a moment to `https://cdn.jsdelivr.net/npm/luckysheet/dist/`. But now I really use the latest snapshot and the problems are different:
````
resize.js:20 Uncaught TypeError: Cannot read property 'offsetHeight' of null
    at luckysheetsizeauto (resize.js:20)
    at Object.resize (api.js:4626)
    at ?guest=:153
luckysheetsizeauto @ resize.js:20
resize @ api.js:4626
(anonymous) @ ?guest=:153
?guest=:331 
````

I also attach the resulting screenshot. The toolbar is now much wider than the sheet, and thus the horizontal scrollbar.

![luckysheet](https://user-images.githubusercontent.com/26835047/95470981-b199a600-0981-11eb-9c88-7403d5c4a932.png)

**Comment by wbfsa** [comment]
The size and location of the luckysheet are determined by the container, if you want to show it at other postion, you can try it.
`
<div style="position:relative; width:300px;height:300px;">
     <div id="luckysheet" style="margin:0px;padding:0px;position:absolute;width:100%;height:100%;left: 0px;top: 0px;"></div>
<div>
`

![20201008221437](https://user-images.githubusercontent.com/68851825/95471282-5af98f80-09b4-11eb-81b4-0818e4a32952.png)

**Comment by d01010101** [comment]
See that the whole widget (the spreadsheet etc.) **scales perfectly to the container**, with the **exception** of the toolbar, so it looks like an internal bug. I use the `div` from the tutorial, which is in another div. Also, it does not explain the error after calling `resize()`: `Cannot read property 'offsetHeight' of null`.

**Comment by d01010101** [comment]
See the screenshot again, without scrolling: the sheet fits perfectly to the external component, but the toolbar is badly drawn and some of its elements escape beyond the right margin (see the previous screenshot). And only these misplaced elements of the toolbar cause that the horizontal scrollbar exists.
![luckysheet](https://user-images.githubusercontent.com/26835047/95472726-aba4c480-0983-11eb-9215-96aefa315e63.png)

**Comment by wbfsa** [comment]
Because luckysheet is loaded with a delay, if luckysheet.create is followed by resize(), an error will be reported. 
You can try change config to hide menu. for example:
```
luckysheet.create({
  showtoolbar:false,
  showinfobar:false,
  showsheetbar:false,
  showstatisticBar:false
});
```

**Comment by wbfsa** [comment]
Can you try the following code? relative is necessary. 
```
<div style="position: relative;height: 500px;width: 500px;">
      <div id="luckysheet" style="margin:0px;padding:0px;position:absolute;width:100%;height:100%;left: 0px;top: 0px;"></div>
</div>
```

**Comment by d01010101** [comment]
I would not want to hide the toolbar, if possible. Anyways, if I call `resize()` before `create()`, it also produces an error:
````
resize.js:20 Uncaught TypeError: Cannot read property 'offsetHeight' of null
    at luckysheetsizeauto (resize.js:20)
    at Object.resize (api.js:4626)
    at HTMLDocument.<anonymous> (?guest=:151)
    at r (plugin.js:1)
    at Object.fireWith [as resolveWith] (plugin.js:1)
    at Function.ready (plugin.js:1)
    at HTMLDocument.B (plugin.js:1)
````
If I call it after `create()`, the error is still there, but at least the spreadsheet actually resizes.

I have put into widget into `<div style="position: relative;height: 500px;width: 500px;">` and I made sure that the position is relative. Now the spreadsheet is smaller and rectangular. I attach the screenshot. But the toolbar is still much wider than 500px and has drawing problems.
![luckysheet](https://user-images.githubusercontent.com/26835047/95474832-e3ad0700-0985-11eb-9a29-f44c56e285dd.png)

**Comment by wbfsa** [comment]
Luckysheet is an excel-like spreadsheet, which may not be the same as a traditional table, so the number and size of cells are determined by the user. If you want to not display the horizontal scroll bar, you can only achieve it by setting the number of cells and column width.

sheet:
{
  column:100, // Number of columns
  row:100, //  Number of rows
  defaultColWidth:73, // width of  columns
  defaultRowHeight:19,// height of  rows
}

Currently these need to be calculated by yourself, because we are not currently considering using it as a regular table. ^ ^

**Comment by wbfsa** [comment]
> the toolbar is still much wider than 500px and has drawing problems.
Regarding the toolbar, my performance here is correct. you can try like this:
```
lucksheet.create(...);
setTimeout(()=>{
   lucksheet.resize();
}, 1000);
```

**Comment by d01010101** [comment]
The horizontal scrollbar of the spreadsheet itself is of course normal. I was speaking about the horizontal scrollbar added by the browser because of the too-wide toolbar.

I will try your code tomorrow. But why won't you replace the delay with some lock inside the code, which waits asynchronously for the spreadsheet code to fully load?

**Comment by d01010101** [comment]
As of `resize()`, it was my fault, it was not really called after `create()`. As of scaling, the problem is still there, but caused by the toolbar which is too wide. I will thus close this bug and open another about the toolbar.
