### ISSUE TITLE
[BUG]当存在冻结行时，更新冻结行单元格的值错误

### ISSUE THREAD

**Issue by sunc0323** [mengshukeji/Luckysheet#67]
**描述错误**
当存在冻结行时，编辑冻结行单元格的值，结果未冻结的行单元格的值被修改

**重现**
冻结前5行，滚动到页面下方，此时单击D5进行编辑，结果D9的值被更改

**期望的结果**
能准确更新未冻结行的值。

**屏幕截图或演示**
![image](https://user-images.githubusercontent.com/23629147/95573217-b2076f00-0a5d-11eb-8918-16882a7637c1.png)
![image](https://user-images.githubusercontent.com/23629147/95573227-b7fd5000-0a5d-11eb-8b3f-b343885c0112.png)

**Comment by wbfsa** [comment]
冻结是初始化的时候通过参数加上的？

**Comment by sunc0323** [comment]
> 冻结是初始化的时候通过参数加上的？

通过工具栏操作和初始化参数都有一样的问题
