### ISSUE TITLE
[BUG]A problem with closing/opening another sheet

### ISSUE THREAD

**Issue by d01010101** [mengshukeji/Luckysheet#70]
I was testing closing an old sheet and loading a new one in the same component. I am not sure of the method, but I tried a sequence of `destroy()`, `create()`, `resize()` on an already open spreadsheet. This properly replaced the existing sheet with a new one. However, the browser console also reported an error. I attach the screenshot:
![luckysheet](https://user-images.githubusercontent.com/26835047/95581137-c2f1b980-0a38-11eb-8e28-00e5cf0e19e0.png)

**Comment by wbfsa** [comment]
I did not find a similar problem, the attachment is the operation video. Can you reproduce it too?
[bandicam 2020-10-10 21-07-01-208.zip](https://github.com/mengshukeji/Luckysheet/files/5359002/bandicam.2020-10-10.21-07-01-208.zip)

**Comment by d01010101** [comment]
If there is a delay between the commands, it works:
````
luckysheet.destroy();
luckysheet.create(options);
setTimeout( ()=>{ luckysheet.resize(); }, 1000 );
````
But without the delay, even if `luckysheet` is already fully loaded from the network and working, there is the error in question:
````
luckysheet.destroy();luckysheet.create(options);luckysheet.resize();
````
Try the latter in the console.

**Comment by mengshukeji** [comment]
Please test the latest version
