### ISSUE TITLE
[BUG]Add missing dependency to the documentation

### ISSUE THREAD

**Issue by d01010101** [mengshukeji/Luckysheet#71]
In *documentation/Steps for usage* there is a missing dependency `<link rel='stylesheet' href='sheet/assets/iconfont/iconfont.css' />`. Without this dependency, the toolbar and some other components display incorrectly.

**Comment by wbfsa** [comment]
Ok

**Comment by mengshukeji** [comment]
Thank you for discovering our mistake, we have fixed the document.
