### ISSUE TITLE
[BUG]Toolbar does not shorten properly if page width is too small

### ISSUE THREAD

**Issue by d01010101** [mengshukeji/Luckysheet#72]
In the current snapshot, even if the label "More..." is properly placed at the right margin, the toolbar icons are still displayed below and to the right of the label:
![luckysheet](https://user-images.githubusercontent.com/26835047/95590851-dc016700-0a46-11eb-82aa-63b9462c132b.png)

This makes the whole component too wide. Possibly caused by the spreadsheet being displayed in a `div` which is smaller than the entire web page.

**Comment by wbfsa** [comment]
Can you post your HTML and CSS code?

**Comment by d01010101** [comment]
I tried to save the page as HTML/CSS but it does not work, because this is a web app which requires a server. Anyway, Luckysheet is in a tab which is not always visible. These are run-of-the-mill tabs similar to these: https://www.w3schools.com/w3css/w3css_tabulators.asp. When the tab is clicked, the following is called:
````
tab.style.display = 'block';
luckysheet.resize();
````
Calling resize() after a delay of one second does not help.

When the tab is initially invisible, the show/hide icon code thinks that Luckysheet is larger (previous screenshot).
When the tab is visible from the beginning, the show/hide icon code thinks that Luckysheet is smaller:
![luckysheet](https://user-images.githubusercontent.com/26835047/95597457-f17a8f00-0a4e-11eb-815d-f0f7f2a450c2.png)
So there is some problem with determining of the component's width. However, Luckysheet scales itself correctly with the exception of the show/hide icon code.

**Comment by d01010101** [comment]
I have sent the HTML/CSS to mengshu@office2.cn. As I said, it does not work reliably without a server, but possibly you will get something out of it.

**Comment by wbfsa** [comment]
d01010101, send to this email address: qwbfsa@gmail.com

**Comment by mengshukeji** [comment]
Please test the latest version
