### ISSUE TITLE
[QUESTION]How to get data from all tabs in JSON

### ISSUE THREAD

**Issue by d01010101** [mengshukeji/Luckysheet#73]
Hello, I would like to get all cell data (not parameters of the sheet) shown in the component, that is, contents of all tabs, in some text format, preferably JSON but not necessarily. There are methods like `getRangeValue` but they return a concrete rectangular region, by default what is selected. Is there any shortcut to get the contents of all tabs?

**Comment by mengshukeji** [comment]
Hi, You an try `luckysheet.getluckysheetfile()`
