### ISSUE TITLE
可否整个中文界面

### ISSUE THREAD

**Issue by gdtool** [mengshukeji/Luckysheet#76]
毕竟国人开发的

**Comment by danielcai1987** [comment]
有中文界面，在初始化设置 **lang: "zh"**
参考文档
https://mengshukeji.github.io/LuckysheetDocs/zh/guide/config.html#%E9%85%8D%E7%BD%AE%E9%A1%B9[https://mengshukeji.github.io/LuckysheetDocs/zh/guide/config.html#%E9%85%8D%E7%BD%AE%E9%A1%B9](url)

**Comment by gdtool** [comment]
原来如此
