### ISSUE TITLE
[BUG]文本型数字的单元格编辑后格式变回到数字

### ISSUE THREAD

**Issue by SuyongSun** [mengshukeji/Luckysheet#79]
**描述错误**
文本型数字的单元格编辑后格式变回到数字。原因是重新进入编辑状态左上角的单引号消失，致使格式丢失。

**截图**
![image](https://user-images.githubusercontent.com/12286518/95695279-d5523a00-0c68-11eb-8941-2e17c2556fd0.png)
![image](https://user-images.githubusercontent.com/12286518/95695289-da16ee00-0c68-11eb-9ea1-a430b9e13cdb.png)
![image](https://user-images.githubusercontent.com/12286518/95695297-ddaa7500-0c68-11eb-908c-939a757a8fea.png)

**Comment by wbfsa** [comment]
已经修复
