### ISSUE TITLE
数据回填的时候，设置的公式会失效

### ISSUE THREAD

**Issue by hejintaoaiyulan** [mengshukeji/Luckysheet#8]
通过getluckysheet方法遍历里面的数据，把所有的内容填写到v字段中保存，公式f也存在，再保存r和c字段，存到数据库中，再从服务端取得数据之后回填，会发现公式格子中，公式存在，但是无法进行计算

**Comment by liuyang3688** [comment]
回填的时候 要自己应用公式吧 execFunction

**Comment by mengshukeji** [comment]
@liuyang3688 的说法是对的，暂时执行下公式。感谢。
