### ISSUE TITLE
[Feature request]是否可以提供服务端相关的能力

### ISSUE THREAD

**Issue by hiNISAL** [mengshukeji/Luckysheet#82]
在一些场景上，如批量生成 excel，在生产环境下不能交给浏览器去处理。

这时候就需要服务端去生成 excel。

是否可以提供相关的 API，谢谢。

**Comment by reatang** [comment]
服务端生成 excel 已经有很多组件了，应该不需要这个库来做。

**Comment by hiNISAL** [comment]
> 服务端生成 excel 已经有很多组件了，应该不需要这个库来做。

但是可能是客户端用户使用LuckySheet生成了许多excel
对应的 json 信息保存在服务端，这时候想要批量打包下载，就需要服务端来完成这个工作，这时候就需要对 json 进行解析。

是想应对这样的场景，当然如果第三方库可以解析 LuckySheet 导出的json数据，那就完全没问题，可以实现这个需求。

**Comment by reatang** [comment]
嗯，也希望作者大大可以将数据结构的格式文档尽早的提供出来，好让对应语言的开发者可以做一些转换插件。

**Comment by wbfsa** [comment]
luckysheet.getLuckysheetfile()可获取全部配置
