### ISSUE TITLE
[Feature request]优化，希望初始化的时候不用点击选中的单元格能直接编辑

### ISSUE THREAD

**Issue by sunc0323** [mengshukeji/Luckysheet#83]
通过luckysheet_select_save初始化选中的单元格或luckysheet.setRangeShow('A2:A2')方法选的中单元格，必须通过鼠标再次点击才能输入编辑，希望可以不用点击就能直接键盘输入编辑。

**Comment by mengshukeji** [comment]
将会提供一个API：enterEditMode进入编辑模式

**Comment by Dushusir** [comment]
如果你想进入编辑模式更改A2单元格的值，初始化后直接使用API即可实现：
第一步：
`luckysheet.setRangeShow('A2')`
第二步：
`luckysheet.enterEditMode()`
