### ISSUE TITLE
[BUG] vue 版本的  图表生成报错，ga.createChart is not a function

### ISSUE THREAD

**Issue by gethubHanSo** [mengshukeji/Luckysheet#844]
vue 版本的  图表生成报错，ga.createChart is not a function  大家这个问题是怎么解决的？
![image](https://user-images.githubusercontent.com/18474018/141453332-35d35fa6-ab07-49d6-8373-9a7c4a15ec25.png)

**Comment by gethubHanSo** [comment]
已解决

**Comment by hmperezt** [comment]
hello, did you solve this?

**Comment by oirobot-github** [comment]
怎么解决的啊

**Comment by aitexiaoy** [comment]
检查插件资源js路径是否正确
