### ISSUE TITLE
[BUG]Text wrapping is not working properly

### ISSUE THREAD

**Issue by eiyu** [mengshukeji/Luckysheet#88]
**Describe the bug**
Usualy When you want to wrap a text in a shell the next word that is out of bound will be moved to the bottom,

**To Reproduce**
1. create a sentence / 2 words
2. resize cell to smaller than the sentence / words length
3. text wrap -> wrap 
4. The sentence/words is not wrapped properly
**What is expected?**
As I mentioned in description the next word that out of bound is not moved to the bottom

**Screenshots or demo**
![Screen Shot 2020-10-14 at 10 23 53 PM](https://user-images.githubusercontent.com/2733614/96010639-3dbd3900-0e6c-11eb-95b5-fb1671be536e.png)

**Environment**
 - OS: Mac
 - Browser Version: Version 86.0.4240.75 (Official Build) (x86_64)
 - Luckysheet Version: demo

**Comment by wbfsa** [comment]
Ok, we will fix it

**Comment by wbfsa** [comment]
Fixed

**Comment by eiyu** [comment]
Nice

**Comment by kvengl** [comment]
This problem is still relevant
