### ISSUE TITLE
通过CDN引入，现在资源访问不到，全部报错？[BUG]发现了个bug

### ISSUE THREAD

**Issue by lengyuxian** [mengshukeji/Luckysheet#898]
**描述错误**

通过CDN方式引入插件，但是现在全部报红，资源访问不到，请问是怎么回事？
还有，这个引入方式能优化一下吗，不管是CDN还是相对路径引入都不怎么方便和美观，建议能放到NPM库最好啦

**重现**

1. 第一步操作:通过CDN方式引入资源
2. 第二步操作:启动项目
3. 第三步操作:刷新页面，发现资源请求不到
4. 最后看到了什么错误:
![image](https://user-images.githubusercontent.com/29294854/146734456-aab1ee2d-71f9-4d3b-a5b2-e6b3bab2ea4b.png)
GET https://cdn.jsdelivr.net/npm/luckysheet@latest/dist/plugins/js/plugin.js net::ERR_CERT_COMMON_NAME_INVALID

**期望的结果**

**屏幕截图或演示**

**环境：**
  - 操作系统：
  - 浏览器 版本号：Chrome 96.0.4664.110（正式版本） （64 位）
  - Luckysheet版本：最新

**备注**

**Comment by huqijie** [comment]
我也是，现在公司使用该模块的页面都瘫痪了

**Comment by lsh-sihong** [comment]
clone代码，执行build后放到本地访问就可以了

**Comment by lengyuxian** [comment]
现在好了，听说是资源证书放错了，导致访问不到，现在已恢复。
但是还是希望能放到npm库方便下载访问吧，远程访问确实不稳定，而且加载事件有时候会很长，有20几秒。放在本地访问吧，文件还挺大的，希望官方团队能早些想出合适的存放方法。
编辑器很强大，望越来越好。
