### ISSUE TITLE
建议：有关excel导入导出

### ISSUE THREAD

**Issue by SuyongSun** [mengshukeji/Luckysheet#9]
目前各类开源表格控件中对于excel的导入导出大多是用sheetjs，但是sheetjs的开源版在样式上读取不完整，可以考虑exceljs这个开源库，是目前已知的对于excel格式读取较完整全面的开源库。

**Comment by liuyang3688** [comment]
会采纳该建议 谢谢

**Comment by mengshukeji** [comment]
> 目前各类开源表格控件中对于excel的导入导出大多是用sheetjs，但是sheetjs的开源版在样式上读取不完整，可以考虑exceljs这个开源库，是目前已知的对于excel格式读取较完整全面的开源库。

很好的建议。针对简单数据的导入导出可以参考：

1. Luckysheet导入: https://www.cnblogs.com/DuShuSir/p/13179483.html
2. Luckysheet导出 : https://www.cnblogs.com/recode-hyh/p/13168226.html

团队正在规划纯前端完全匹配excel格式文件的导入导出库，后续欢迎关注。

**Comment by Ares-Stone** [comment]
> > 目前各类开源表格控件中对于excel的导入导出大多是用sheetjs，但是sheetjs的开源版在样式上读取不完整，可以考虑exceljs这个开源库，是目前已知的对于excel格式读取较完整全面的开源库。
> 
> 很好的建议。针对简单数据的导入导出可以参考：
> 
> 1. Luckysheet导入: https://www.cnblogs.com/DuShuSir/p/13179483.html
> 2. Luckysheet导出 : https://www.cnblogs.com/recode-hyh/p/13168226.html
> 
> 团队正在规划纯前端完全匹配excel格式文件的导入导出库，后续欢迎关注。
