### ISSUE TITLE
[Feature request]我有个点子

### ISSUE THREAD

**Issue by nuan1989** [mengshukeji/Luckysheet#90]
**您的功能请求与问题有关吗？**
想不到你的项目已经快4k了. 
我希望可以设置纸张大小, 如A4的大小虚线标识. 另外一个api有点少. 
很厉害的项目, 持续关注中...

**描述您想要的解决方案**

**其他内容**

**Comment by wbfsa** [comment]
功能太多，来不及写。 打印正在做了，目标是和excel的打印一致，有分页线标识。

**Comment by nuan1989** [comment]
牛逼的项目

**Comment by nuan1989** [comment]
国内目前为止, web-excel目前还没一个项目能跟你的比, 多数都是打打闹闹就夭折了.

**Comment by nuan1989** [comment]
大佬, 能否多关照一下中文啊, 看你界面都是英文的.

**Comment by yaobo-lab** [comment]
> 打印正在做了，目标是和excel的打印一致，有分页线

预计打印什么时候出？
