### ISSUE TITLE
如何与js交互呢？比如想通过js的把数据传到表格里，或者想把表格里的数据转化成js？

### ISSUE THREAD

**Issue by radtymm** [mengshukeji/Luckysheet#95]
如何与js交互呢？比如想通过js的把数据传到表格里，或者想把表格里的数据转化成js？

**Comment by mengshukeji** [comment]
1. **把数据传到表格里**
可以使用我们的初始化方法`luckytsheet.create()`传入数据

2. **表格里的数据转化成js**
js我理解为是一门开发语言，数据如何转化为一门语言可能不是很通顺。数据转化可以参考：[transToCellData](https://mengshukeji.github.io/LuckysheetDocs/zh/guide/api.html#transtocelldata-data-setting)
