### ISSUE TITLE
[BUG] It seems that the Cooperative editing demo does not work

### ISSUE THREAD

**Issue by reeingal** [mengshukeji/Luckysheet#991]
The Cooperative editing demo seems not work, I get `Uncaught SyntaxError: expected expression, got ')'` error in the console of Firefox.

I just want to check the data return from `loadurl` api in the demo, because I get error in my local test.

**Comment by reeingal** [comment]
I resolved the error in my local test. The problem was that I returned a JSON object, not a JSON string.

**Comment by mengshukeji** [comment]
The abnormal data format will cause some errors in the backend, which has been restarted and repaired
